"""Discovery spec for aws_cloudtrail. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "aws_cloudtrail",
        "display_name": "AWS CloudTrail",
        "vendor": "AWS",
        "product": "CloudTrail",
        "description": "AWS CloudTrail records API calls made across an AWS account, capturing the identity, source, request parameters, and response elements for management and data events in JSON format.",
    },

    "category": "cloud",
    "source_groups": ["cloud"],

    "format": {
        "type": "json",
        "confidence": 0.98,
        "delimiter": None,
        "kv_separator": None,
        "quoted_values": True,
        "timestamp_fields": ["eventTime"],
        "timestamp_format": "ISO 8601 UTC (YYYY-MM-DDTHH:MM:SSZ)",
    },

    "sourcetype": {
        "name": "aws:cloudtrail",
        "confidence": 0.98,
        "origin": "Splunkbase TA (app 1876) — Splunk Add-on for AWS",
    },

    "fields": [
        # --- Core record identifiers ---
        {"name": "eventVersion", "type": "string", "required": True, "example": "1.08", "confidence": 1.0, "description": "Version of the log event format"},
        {"name": "eventTime", "type": "string", "required": True, "example": "2026-04-12T14:22:17Z", "confidence": 1.0, "description": "ISO 8601 UTC time the request was completed"},
        {"name": "eventSource", "type": "string", "required": True, "example": "s3.amazonaws.com", "confidence": 1.0, "description": "AWS service endpoint that the request was made to"},
        {"name": "eventName", "type": "string", "required": True, "example": "GetObject", "confidence": 1.0, "description": "Name of the API action"},
        {"name": "awsRegion", "type": "string", "required": True, "example": "us-east-1", "confidence": 1.0, "description": "AWS region the request was made to"},
        {"name": "sourceIPAddress", "type": "ipv4", "required": True, "example": "203.0.113.24", "confidence": 1.0, "description": "IP address that the request was made from"},
        {"name": "userAgent", "type": "string", "required": True, "example": "aws-cli/2.15.0 Python/3.11 Linux/5.15", "confidence": 1.0, "description": "Agent through which the request was made"},
        {"name": "requestID", "type": "string", "required": True, "example": "EXAMPLE-1a2b3c4d-5e6f-7890-abcd-ef0123456789", "confidence": 1.0, "description": "Value generated by the service to identify the request"},
        {"name": "eventID", "type": "string", "required": True, "example": "b1f9e1a7-8c0f-4f8b-9e3a-1d2c3b4a5e6f", "confidence": 1.0, "description": "GUID generated by CloudTrail to uniquely identify each event"},
        {"name": "eventType", "type": "string", "required": True, "example": "AwsApiCall", "confidence": 1.0, "description": "Type of event: AwsApiCall, AwsServiceEvent, AwsConsoleSignIn"},
        {"name": "recipientAccountId", "type": "string", "required": True, "example": "123456789012", "confidence": 1.0, "description": "Account ID that received the event"},
        {"name": "managementEvent", "type": "bool", "required": False, "example": "true", "confidence": 0.9, "description": "Whether the event is a management event"},
        {"name": "readOnly", "type": "bool", "required": False, "example": "true", "confidence": 0.9, "description": "Whether the operation is read-only"},
        {"name": "eventCategory", "type": "string", "required": False, "example": "Management", "confidence": 0.9, "description": "Event category: Management, Data, Insight"},

        # --- userIdentity (nested object) ---
        {"name": "userIdentity.type", "type": "string", "required": True, "example": "IAMUser", "confidence": 1.0, "description": "Type of identity: Root, IAMUser, AssumedRole, FederatedUser, AWSAccount, AWSService"},
        {"name": "userIdentity.principalId", "type": "string", "required": True, "example": "AIDAEXAMPLE1234567890", "confidence": 1.0, "description": "Unique identifier of the entity that made the call"},
        {"name": "userIdentity.arn", "type": "string", "required": True, "example": "arn:aws:iam::123456789012:user/alice", "confidence": 1.0, "description": "ARN of the principal that made the call"},
        {"name": "userIdentity.accountId", "type": "string", "required": True, "example": "123456789012", "confidence": 1.0, "description": "Account that owns the entity that made the call"},
        {"name": "userIdentity.userName", "type": "string", "required": False, "example": "alice", "confidence": 0.9, "description": "Friendly name of the identity that made the call"},
        {"name": "userIdentity.accessKeyId", "type": "string", "required": False, "example": "AKIAEXAMPLE1234567890", "confidence": 0.9, "description": "Access key ID used to sign the request"},
        {"name": "userIdentity.sessionContext.attributes.mfaAuthenticated", "type": "string", "required": False, "example": "true", "confidence": 0.7, "description": "Whether MFA was used"},
        {"name": "userIdentity.sessionContext.attributes.creationDate", "type": "string", "required": False, "example": "2026-04-12T13:00:00Z", "confidence": 0.7, "description": "When the session was issued"},

        # --- Request / response ---
        {"name": "requestParameters", "type": "json", "required": False, "example": '{"bucketName":"example-bucket","key":"path/to/object.txt"}', "confidence": 0.9, "description": "Parameters that were sent with the request"},
        {"name": "responseElements", "type": "json", "required": False, "example": "null", "confidence": 0.8, "description": "Response elements returned by the service"},
        {"name": "errorCode", "type": "string", "required": False, "example": "AccessDenied", "confidence": 0.7, "description": "AWS service error code if the request returned an error"},
        {"name": "errorMessage", "type": "string", "required": False, "example": "User is not authorized to perform this action", "confidence": 0.7, "description": "Error message if the request failed"},
        {"name": "resources", "type": "json", "required": False, "example": '[{"accountId":"123456789012","type":"AWS::S3::Object","ARN":"arn:aws:s3:::example-bucket/path/to/object.txt"}]', "confidence": 0.7, "description": "List of resources accessed by the request"},
        {"name": "tlsDetails.tlsVersion", "type": "string", "required": False, "example": "TLSv1.2", "confidence": 0.7, "description": "TLS version used in the request"},
        {"name": "tlsDetails.cipherSuite", "type": "string", "required": False, "example": "ECDHE-RSA-AES128-GCM-SHA256", "confidence": 0.7, "description": "Cipher suite used in the request"},
    ],

    "sample_events": [
        {
            "raw": '{"eventVersion":"1.08","userIdentity":{"type":"IAMUser","principalId":"AIDAEXAMPLE1234567890","arn":"arn:aws:iam::123456789012:user/alice","accountId":"123456789012","userName":"alice","accessKeyId":"AKIAEXAMPLE1234567890"},"eventTime":"2026-04-12T14:22:17Z","eventSource":"s3.amazonaws.com","eventName":"GetObject","awsRegion":"us-east-1","sourceIPAddress":"203.0.113.24","userAgent":"aws-cli/2.15.0 Python/3.11 Linux/5.15","requestParameters":{"bucketName":"example-bucket","key":"path/to/object.txt"},"responseElements":null,"requestID":"EXAMPLE-1a2b3c4d-5e6f-7890-abcd-ef0123456789","eventID":"b1f9e1a7-8c0f-4f8b-9e3a-1d2c3b4a5e6f","readOnly":true,"eventType":"AwsApiCall","managementEvent":false,"recipientAccountId":"123456789012","eventCategory":"Data"}',
            "subtype": "data_read",
        },
        {
            "raw": '{"eventVersion":"1.08","userIdentity":{"type":"AssumedRole","principalId":"AROAEXAMPLE:session-bob","arn":"arn:aws:sts::123456789012:assumed-role/DevOps/session-bob","accountId":"123456789012","sessionContext":{"attributes":{"mfaAuthenticated":"true","creationDate":"2026-04-12T13:00:00Z"}}},"eventTime":"2026-04-12T14:30:05Z","eventSource":"iam.amazonaws.com","eventName":"CreateUser","awsRegion":"us-east-1","sourceIPAddress":"198.51.100.7","userAgent":"console.amazonaws.com","requestParameters":{"userName":"charlie"},"responseElements":{"user":{"userName":"charlie","userId":"AIDAEXAMPLENEWUSER","arn":"arn:aws:iam::123456789012:user/charlie"}},"requestID":"EXAMPLE-aaaa-bbbb-cccc-ddddeeeeffff","eventID":"c2d3e4f5-6a7b-8c9d-0e1f-2a3b4c5d6e7f","eventType":"AwsApiCall","managementEvent":true,"recipientAccountId":"123456789012","eventCategory":"Management"}',
            "subtype": "management_write",
        },
        {
            "raw": '{"eventVersion":"1.08","userIdentity":{"type":"IAMUser","principalId":"AIDAEXAMPLEBADACTOR","arn":"arn:aws:iam::123456789012:user/eve","accountId":"123456789012","userName":"eve"},"eventTime":"2026-04-12T15:02:44Z","eventSource":"ec2.amazonaws.com","eventName":"TerminateInstances","awsRegion":"us-west-2","sourceIPAddress":"192.0.2.55","userAgent":"Boto3/1.34.0","errorCode":"Client.UnauthorizedOperation","errorMessage":"You are not authorized to perform this operation.","requestParameters":{"instancesSet":{"items":[{"instanceId":"i-0abcdef1234567890"}]}},"responseElements":null,"requestID":"EXAMPLE-99887766-5544-3322-1100-aabbccddeeff","eventID":"d5e6f7a8-9b0c-1d2e-3f4a-5b6c7d8e9f0a","eventType":"AwsApiCall","managementEvent":true,"recipientAccountId":"123456789012","eventCategory":"Management","readOnly":false}',
            "subtype": "management_denied",
        },
    ],

    "generator_hints": {
        "module_name": "generate_aws_cloudtrail",
        "function_name": "generate_aws_cloudtrail_logs",
        "volume_category": "cloud_audit",
        "baseline_events_per_day": 2000,
        "subtypes": ["data_read", "data_write", "management_read", "management_write", "management_denied", "console_signin"],
        "subtype_weights": {"data_read": 40, "data_write": 15, "management_read": 25, "management_write": 10, "management_denied": 5, "console_signin": 5},
        "services": ["s3.amazonaws.com", "ec2.amazonaws.com", "iam.amazonaws.com", "sts.amazonaws.com", "lambda.amazonaws.com", "kms.amazonaws.com", "cloudformation.amazonaws.com", "dynamodb.amazonaws.com"],
        "regions": ["us-east-1", "us-east-2", "us-west-1", "us-west-2", "eu-west-1", "eu-central-1", "ap-southeast-1", "ap-northeast-1"],
        "identity_types": ["IAMUser", "AssumedRole", "AWSService", "Root", "FederatedUser"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-user-identity.html", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/1876", "kind": "splunkbase", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 74,
        "overall_confidence": 0.95,
    },
}
