"""Discovery spec for cisco_webex. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "cisco_webex",
        "display_name": "Cisco Webex Events",
        "vendor": "Cisco",
        "product": "Cisco Webex",
        "description": "Cisco Webex collaboration events pulled from the Webex REST API: scheduled meetings, admin audit events, security (login) audit events, and meeting quality metrics. All events are emitted as JSON with ISO 8601 timestamps.",
    },

    "category": "collaboration",
    "source_groups": ["collaboration", "cloud", "saas"],

    "format": {
        "type": "json",
        "confidence": 0.85,
        "timestamp_fields": ["start", "created", "joinTime", "meetingStartTime"],
        "timestamp_format": "ISO 8601 (YYYY-MM-DDTHH:MM:SS.sssZ) for REST API events; MM/DD/YYYY HH:MM:SS for legacy XML API meeting usage",
    },

    "sourcetype": {
        "name": "cisco:webex:meetings",
        "confidence": 0.80,
        "origin": "GitHub repo (github.com/splunk/cisco-webex-add-on-for-splunk) — no official Splunkbase app",
        "related_sourcetypes": [
            "cisco:webex:meetings",
            "cisco:webex:admin:audit:events",
            "cisco:webex:security:audit:events",
            "cisco:webex:meeting:qualities",
            "cisco:webex:call:detailed_history",
            "cisco:webex:meetings:history:meetingusagehistory",
            "cisco:webex:meetings:history:meetingattendeehistory",
        ],
    },

    "fields": [
        # --- Core meeting fields (cisco:webex:meetings) ---
        {"name": "id", "type": "string", "required": True, "example": "870f51ff287b41be84648c2b4b8b6c3c", "confidence": 0.95, "description": "Unique meeting UUID"},
        {"name": "meetingNumber", "type": "string", "required": True, "example": "123456789", "confidence": 0.95, "description": "Nine-digit Webex meeting number"},
        {"name": "title", "type": "string", "required": True, "example": "Sprint Planning", "confidence": 0.95, "description": "Meeting title shown in calendar invites"},
        {"name": "agenda", "type": "string", "required": False, "example": "Plan upcoming sprint tasks", "confidence": 0.80, "description": "Free-text meeting agenda"},
        {"name": "meetingType", "type": "string", "required": True, "example": "scheduledMeeting", "confidence": 0.90, "description": "Meeting type: scheduledMeeting, meetingSeries, scheduledMeetingInstance"},
        {"name": "state", "type": "string", "required": True, "example": "ended", "confidence": 0.90, "description": "Meeting lifecycle state: scheduled, ready, inProgress, ended, missed"},
        {"name": "timezone", "type": "string", "required": True, "example": "America/New_York", "confidence": 0.90, "description": "IANA timezone for meeting start/end"},
        {"name": "start", "type": "timestamp", "required": True, "example": "2026-04-12T14:00:00Z", "confidence": 0.95, "description": "Meeting start time (ISO 8601)"},
        {"name": "end", "type": "timestamp", "required": True, "example": "2026-04-12T15:30:00Z", "confidence": 0.95, "description": "Meeting end time (ISO 8601)"},
        {"name": "hostUserId", "type": "string", "required": True, "example": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS9hYmMxMjM=", "confidence": 0.90, "description": "Base64-encoded ciscospark:// URI identifying host"},
        {"name": "hostDisplayName", "type": "string", "required": True, "example": "Jane Doe", "confidence": 0.95, "description": "Display name of the meeting host"},
        {"name": "hostEmail", "type": "string", "required": True, "example": "jane.doe@example.com", "confidence": 0.95, "description": "Email address of the meeting host"},
        {"name": "siteUrl", "type": "string", "required": True, "example": "example.webex.com", "confidence": 0.95, "description": "Webex site URL the meeting was hosted on"},
        {"name": "webLink", "type": "string", "required": False, "example": "https://example.webex.com/meet/jane.doe", "confidence": 0.85, "description": "Browser join link for the meeting"},
        {"name": "sipAddress", "type": "string", "required": False, "example": "123456789@example.webex.com", "confidence": 0.80, "description": "SIP dial-in address for the meeting"},
        {"name": "enabledJoinBeforeHost", "type": "bool", "required": False, "example": "true", "confidence": 0.75, "description": "Whether participants may join before the host"},
        {"name": "enabledAutoRecordMeeting", "type": "bool", "required": False, "example": "false", "confidence": 0.75, "description": "Whether auto-recording is enabled"},

        # --- Admin/security audit fields (cisco:webex:admin:audit:events, cisco:webex:security:audit:events) ---
        {"name": "created", "type": "timestamp", "required": True, "example": "2026-04-12T14:05:32.123Z", "confidence": 0.95, "description": "Event creation timestamp (ISO 8601 with ms)"},
        {"name": "actorId", "type": "string", "required": True, "example": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS9kZWYxMjM=", "confidence": 0.90, "description": "Base64-encoded ciscospark:// URI for the actor"},
        {"name": "actorOrgId", "type": "string", "required": True, "example": "Y2lzY29zcGFyazovL3VzL09SR0FOSVpBVElPTi8xMjM=", "confidence": 0.90, "description": "Base64-encoded org ID for the actor"},
        {"name": "type", "type": "string", "required": True, "example": "user_management", "confidence": 0.85, "description": "Audit event type: user_management, group_management, meeting_management, compliance_management, device_management, logins"},
        {"name": "data.actorEmail", "type": "string", "required": True, "example": "admin@example.com", "confidence": 0.90, "description": "Email of the user who performed the action (nested)"},
        {"name": "data.actorName", "type": "string", "required": True, "example": "Admin User", "confidence": 0.90, "description": "Display name of the actor (nested)"},
        {"name": "data.actorIp", "type": "ipv4", "required": False, "example": "10.10.30.45", "confidence": 0.85, "description": "Source IP address of the actor (nested)"},
        {"name": "data.actorUserAgent", "type": "string", "required": False, "example": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36", "confidence": 0.80, "description": "HTTP User-Agent string of the actor (nested)"},
        {"name": "data.eventCategory", "type": "string", "required": True, "example": "USERS", "confidence": 0.85, "description": "High-level event category (USERS, GROUPS, MEETINGS, COMPLIANCE, DEVICES, LOGINS)"},
        {"name": "data.eventDescription", "type": "string", "required": True, "example": "User created", "confidence": 0.85, "description": "Human-readable event description"},
        {"name": "data.actionText", "type": "string", "required": False, "example": "Admin User created user John Smith", "confidence": 0.80, "description": "Full action sentence used for CIM 'action' alias"},
        {"name": "data.targetType", "type": "string", "required": False, "example": "USER", "confidence": 0.80, "description": "Type of target object: USER, GROUP, SETTING, DEVICE"},
        {"name": "data.targetName", "type": "string", "required": False, "example": "John Smith", "confidence": 0.80, "description": "Name of the target of the action"},
        {"name": "data.status", "type": "string", "required": False, "example": "success", "confidence": 0.80, "description": "Event outcome (security audit only): success, failure"},
        {"name": "data.trackingId", "type": "string", "required": False, "example": "ATLAS_c81d4e2e-bcf2-11e6-869b-7df92533d2db", "confidence": 0.75, "description": "Webex tracking ID (ATLAS_<uuid>) for correlating audit entries"},

        # --- Meeting quality fields (cisco:webex:meeting:qualities) ---
        {"name": "meetingInstanceId", "type": "string", "required": True, "example": "870f51ff287b41be84648c2b4b8b6c3c_I_123", "confidence": 0.85, "description": "Instance ID of the meeting occurrence"},
        {"name": "webexUserEmail", "type": "string", "required": True, "example": "jane.doe@example.com", "confidence": 0.90, "description": "Email of the participant whose quality is being measured"},
        {"name": "joinTime", "type": "timestamp", "required": True, "example": "2026-04-12T14:00:15.000Z", "confidence": 0.90, "description": "Participant join time (ISO 8601)"},
        {"name": "leaveTime", "type": "timestamp", "required": True, "example": "2026-04-12T15:29:42.000Z", "confidence": 0.90, "description": "Participant leave time (ISO 8601)"},
        {"name": "clientType", "type": "string", "required": True, "example": "Webex Desktop", "confidence": 0.85, "description": "Client type: Webex Desktop, Webex Mobile (iOS), Webex Mobile (Android), Web Browser, Telepresence, Phone (PSTN)"},
        {"name": "clientVersion", "type": "string", "required": False, "example": "43.12.0.1234", "confidence": 0.75, "description": "Webex client version string"},
        {"name": "osType", "type": "string", "required": False, "example": "Windows", "confidence": 0.80, "description": "Operating system type: Windows, macOS, iOS, Android, Linux"},
        {"name": "osVersion", "type": "string", "required": False, "example": "10.0.22621", "confidence": 0.75, "description": "Operating system version"},
        {"name": "networkType", "type": "string", "required": False, "example": "wifi", "confidence": 0.70, "description": "Network type: wifi, ethernet, cellular"},
        {"name": "localIP", "type": "ipv4", "required": False, "example": "10.10.30.45", "confidence": 0.80, "description": "Local/private IP of the participant endpoint"},
        {"name": "publicIP", "type": "ipv4", "required": False, "example": "203.0.113.42", "confidence": 0.80, "description": "Public IP of the participant endpoint"},
        {"name": "serverRegion", "type": "string", "required": False, "example": "San Jose, USA", "confidence": 0.70, "description": "Webex media server region the participant connected to"},
    ],

    "sample_events": [
        {
            "raw": '{"id": "870f51ff287b41be84648c2b4b8b6c3c", "meetingNumber": "123456789", "title": "Sprint Planning", "agenda": "Plan upcoming sprint tasks", "meetingType": "scheduledMeeting", "state": "ended", "timezone": "America/New_York", "start": "2026-04-12T14:00:00Z", "end": "2026-04-12T15:30:00Z", "hostUserId": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS9hYmMxMjM=", "hostDisplayName": "Jane Doe", "hostEmail": "jane.doe@example.com", "hostKey": "482913", "siteUrl": "example.webex.com", "webLink": "https://example.webex.com/meet/jane.doe", "sipAddress": "123456789@example.webex.com", "enabledJoinBeforeHost": true, "joinBeforeHostMinutes": 5, "enabledAutoRecordMeeting": false}',
            "subtype": "cisco:webex:meetings",
        },
        {
            "raw": '{"id": "d1f2e3a4-5b6c-7d8e-9f01-234567890abc", "actorId": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS9kZWYxMjM=", "actorOrgId": "Y2lzY29zcGFyazovL3VzL09SR0FOSVpBVElPTi8xMjM=", "created": "2026-04-12T14:05:32.123Z", "type": "user_management", "data": {"actorName": "Admin User", "actorEmail": "admin@example.com", "actorOrgName": "Example Org", "actorIp": "10.10.30.45", "actorUserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "adminRoles": ["Full_Admin"], "eventCategory": "USERS", "eventDescription": "User created", "targetId": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS94eXo5ODc=", "targetType": "USER", "targetName": "John Smith", "targetOrgId": "Y2lzY29zcGFyazovL3VzL09SR0FOSVpBVElPTi8xMjM=", "targetOrgName": "Example Org", "trackingId": "ATLAS_c81d4e2e-bcf2-11e6-869b-7df92533d2db", "actionText": "Admin User created user John Smith"}}',
            "subtype": "cisco:webex:admin:audit:events",
        },
        {
            "raw": '{"id": "a9b8c7d6-e5f4-3210-9876-543210fedcba", "created": "2026-04-12T08:12:07.456Z", "actorId": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS9oZ2YxMjM=", "actorOrgId": "Y2lzY29zcGFyazovL3VzL09SR0FOSVpBVElPTi8xMjM=", "type": "logins", "data": {"actorName": "Jane Doe", "actorEmail": "jane.doe@example.com", "actorOrgName": "Example Org", "actorIp": "10.10.30.45", "actorUserAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15", "eventCategory": "LOGINS", "eventDescription": "A user logged in", "actionText": "Jane Doe logged into organization Example Org", "status": "success", "trackingId": "ATLAS_7f3e1b9a-1234-4567-89ab-cdef01234567"}}',
            "subtype": "cisco:webex:security:audit:events",
        },
    ],

    "generator_hints": {
        "module_name": "generate_cisco_webex",
        "function_name": "generate_cisco_webex_logs",
        "volume_category": "collaboration",
        "baseline_events_per_day": 300,
        "subtypes": [
            "cisco:webex:meetings",
            "cisco:webex:admin:audit:events",
            "cisco:webex:security:audit:events",
            "cisco:webex:meeting:qualities",
        ],
        "subtype_weights": {
            "cisco:webex:meetings": 25,
            "cisco:webex:admin:audit:events": 10,
            "cisco:webex:security:audit:events": 35,
            "cisco:webex:meeting:qualities": 30,
        },
        "meeting_types": ["scheduledMeeting", "meetingSeries", "scheduledMeetingInstance"],
        "meeting_states": ["scheduled", "ready", "inProgress", "ended", "missed"],
        "audit_categories": ["USERS", "GROUPS", "MEETINGS", "COMPLIANCE", "DEVICES", "LOGINS"],
        "client_types": ["Webex Desktop", "Webex Mobile (iOS)", "Webex Mobile (Android)", "Web Browser", "Telepresence", "Phone (PSTN)"],
        "server_regions": ["San Jose, USA", "Chicago, USA", "London, UK", "Frankfurt, DE", "Tokyo, JP"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://developer.webex.com/docs/api/v1/meetings", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://developer.webex.com/docs/api/v1/admin-audit-events", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://developer.webex.com/docs/api/v1/security-audit-events", "kind": "vendor_doc", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://developer.webex.com/docs/api/v1/meeting-qualities", "kind": "vendor_doc", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://developer.webex.com/", "kind": "vendor_doc", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://github.com/splunk/cisco-webex-add-on-for-splunk", "kind": "github", "trust": 0.75, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "preset",
        "elapsed_sec": 0,
        "overall_confidence": 0.85,
        "notes": "Cisco Webex has no official Splunkbase TA. Field names and sourcetypes derived from the community GitHub add-on (splunk/cisco-webex-add-on-for-splunk) and the Webex Developer Portal REST API schemas. Confidence lowered accordingly.",
    },
}
