"""Discovery spec for crowdstrike_falcon. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "crowdstrike_falcon",
        "display_name": "CrowdStrike Falcon EDR",
        "vendor": "CrowdStrike",
        "product": "Falcon EDR (Event Streams)",
        "description": "CrowdStrike Falcon endpoint detection and response events streamed via the Falcon Streaming API. Events include detection summaries, authentication activity, and user session telemetry delivered as JSON with a metadata envelope and an event payload.",
    },

    "category": "windows",
    "source_groups": ["endpoint", "edr"],

    "format": {
        "type": "json",
        "confidence": 0.95,
        "delimiter": "\n",
        "kv_separator": None,
        "quoted_values": True,
        "timestamp_fields": ["metadata.eventCreationTime", "event.ProcessStartTime"],
        "timestamp_format": "epoch milliseconds (metadata.eventCreationTime), epoch seconds (event.ProcessStartTime)",
    },

    "sourcetype": {
        "name": "crowdstrike:falcon",
        "confidence": 0.95,
        "origin": "Splunkbase TA (app 4700) — CrowdStrike Falcon Event Streams",
    },

    "fields": [
        # --- metadata envelope ---
        {"name": "metadata.customerIDString", "type": "string", "required": True, "example": "a1b2c3d4e5f6g7h8i9j0", "confidence": 1.0, "description": "Falcon CID (customer identifier)"},
        {"name": "metadata.offset", "type": "int", "required": True, "example": "1928374", "confidence": 1.0, "description": "Stream offset for the event"},
        {"name": "metadata.eventType", "type": "string", "required": True, "example": "DetectionSummaryEvent", "confidence": 1.0, "description": "Event type: DetectionSummaryEvent, AuthActivityAuditEvent, UserActivityAuditEvent, IncidentSummaryEvent, EppDetectionSummaryEvent"},
        {"name": "metadata.eventCreationTime", "type": "int", "required": True, "example": "1723638138000", "confidence": 1.0, "description": "Event creation time (epoch milliseconds)"},
        {"name": "metadata.version", "type": "string", "required": True, "example": "1.0", "confidence": 1.0, "description": "Schema version of the event"},

        # --- detection summary event body ---
        {"name": "event.ProcessStartTime", "type": "int", "required": False, "example": "1723638130", "confidence": 0.9, "description": "Process start time (epoch seconds)"},
        {"name": "event.ProcessEndTime", "type": "int", "required": False, "example": "0", "confidence": 0.7, "description": "Process end time (epoch seconds), 0 if still running"},
        {"name": "event.ProcessId", "type": "int", "required": False, "example": "4812", "confidence": 0.9, "description": "Operating system process ID"},
        {"name": "event.ParentProcessId", "type": "int", "required": False, "example": "2312", "confidence": 0.8, "description": "Parent process ID"},
        {"name": "event.ComputerName", "type": "string", "required": True, "example": "WS-ENG-0073", "confidence": 1.0, "description": "Hostname of the endpoint where the detection occurred"},
        {"name": "event.Hostname", "type": "string", "required": False, "example": "WS-ENG-0073", "confidence": 0.9, "description": "Hostname alias (same as ComputerName)"},
        {"name": "event.UserName", "type": "string", "required": True, "example": "CORP\\\\jsmith", "confidence": 1.0, "description": "User context under which the event occurred"},
        {"name": "event.DetectName", "type": "string", "required": True, "example": "SuspiciousProcessExecution", "confidence": 1.0, "description": "Short name of the detection"},
        {"name": "event.DetectDescription", "type": "string", "required": True, "example": "A process attempted to dump credentials using a known LSASS access pattern.", "confidence": 1.0, "description": "Human-readable description of the detection"},
        {"name": "event.Severity", "type": "int", "required": True, "example": "4", "confidence": 1.0, "description": "Severity score from 1 (informational) to 5 (critical)"},
        {"name": "event.SeverityName", "type": "string", "required": True, "example": "High", "confidence": 1.0, "description": "Severity name: Informational, Low, Medium, High, Critical"},
        {"name": "event.Objective", "type": "string", "required": False, "example": "Gain Access", "confidence": 0.8, "description": "Kill-chain objective"},
        {"name": "event.Tactic", "type": "string", "required": True, "example": "Credential Access", "confidence": 1.0, "description": "MITRE ATT&CK tactic name"},
        {"name": "event.TacticId", "type": "string", "required": False, "example": "TA0006", "confidence": 0.9, "description": "MITRE ATT&CK tactic ID"},
        {"name": "event.Technique", "type": "string", "required": True, "example": "OS Credential Dumping", "confidence": 1.0, "description": "MITRE ATT&CK technique name"},
        {"name": "event.TechniqueId", "type": "string", "required": False, "example": "T1003", "confidence": 0.9, "description": "MITRE ATT&CK technique ID"},
        {"name": "event.PatternDispositionDescription", "type": "string", "required": False, "example": "Prevention, process killed.", "confidence": 0.8, "description": "Disposition description (allowed, blocked, killed)"},
        {"name": "event.PatternDispositionValue", "type": "int", "required": False, "example": "2048", "confidence": 0.8, "description": "Numeric disposition bitmask"},

        # --- file/process details ---
        {"name": "event.FileName", "type": "string", "required": True, "example": "mimikatz.exe", "confidence": 1.0, "description": "Name of the offending file"},
        {"name": "event.FilePath", "type": "string", "required": True, "example": "\\\\Device\\\\HarddiskVolume3\\\\Users\\\\jsmith\\\\AppData\\\\Local\\\\Temp\\\\", "confidence": 1.0, "description": "Full path to the offending file"},
        {"name": "event.CommandLine", "type": "string", "required": True, "example": "mimikatz.exe \"privilege::debug\" \"sekurlsa::logonpasswords\" exit", "confidence": 1.0, "description": "Command line used to launch the offending process"},
        {"name": "event.SHA256String", "type": "string", "required": True, "example": "2926dcdbe38a6b5b23a3bdb5c6c8ad3c30e1a79e9a5e8e51e4a5f3b2f9d6c7e1", "confidence": 1.0, "description": "SHA-256 hash of the offending file"},
        {"name": "event.MD5String", "type": "string", "required": False, "example": "a52b9c7d4f8e61b3a04d7c8e9f1b2c3d", "confidence": 0.9, "description": "MD5 hash of the offending file"},
        {"name": "event.SHA1String", "type": "string", "required": False, "example": "6c8e9f1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f", "confidence": 0.8, "description": "SHA-1 hash of the offending file"},
        {"name": "event.MachineDomain", "type": "string", "required": False, "example": "CORP", "confidence": 0.8, "description": "Domain the machine is joined to"},
        {"name": "event.SensorId", "type": "string", "required": True, "example": "b3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8", "confidence": 1.0, "description": "Falcon sensor Agent ID (AID)"},
        {"name": "event.FalconHostLink", "type": "string", "required": False, "example": "https://falcon.crowdstrike.com/activity/detections/detail/b3d4e5f6a7b8c9d0.../2926dcdbe38a...", "confidence": 0.8, "description": "Link to the detection in the Falcon console"},

        # --- network details ---
        {"name": "event.LocalIP", "type": "ipv4", "required": False, "example": "10.24.14.88", "confidence": 0.9, "description": "Local IP address of the sensor"},
        {"name": "event.RemoteIP", "type": "ipv4", "required": False, "example": "185.220.101.14", "confidence": 0.8, "description": "Remote IP address involved in the event"},
        {"name": "event.MACAddress", "type": "string", "required": False, "example": "00-50-56-8d-2b-3c", "confidence": 0.7, "description": "MAC address of the endpoint"},

        # --- identifiers ---
        {"name": "event.EventUUID", "type": "string", "required": True, "example": "e1f2a3b4-c5d6-e7f8-a9b0-c1d2e3f4a5b6", "confidence": 1.0, "description": "Unique event identifier"},
        {"name": "event.DetectId", "type": "string", "required": False, "example": "ldt:b3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8:2926dcdbe38a6b5b23a3bdb5c6c8ad3c", "confidence": 0.9, "description": "Detection identifier used in Falcon UI"},
        {"name": "event.EventId", "type": "int", "required": False, "example": "101", "confidence": 0.8, "description": "Falcon event ID within the stream"},
    ],

    "sample_events": [
        {
            "raw": '{"metadata":{"customerIDString":"a1b2c3d4e5f6g7h8i9j0","offset":1928374,"eventType":"DetectionSummaryEvent","eventCreationTime":1723638138000,"version":"1.0"},"event":{"ProcessStartTime":1723638130,"ProcessEndTime":0,"ProcessId":4812,"ParentProcessId":2312,"ComputerName":"WS-ENG-0073","Hostname":"WS-ENG-0073","UserName":"CORP\\\\jsmith","DetectName":"SuspiciousProcessExecution","DetectDescription":"A process attempted to dump credentials using a known LSASS access pattern.","Severity":4,"SeverityName":"High","Objective":"Gain Access","Tactic":"Credential Access","TacticId":"TA0006","Technique":"OS Credential Dumping","TechniqueId":"T1003","PatternDispositionDescription":"Prevention, process killed.","PatternDispositionValue":2048,"FileName":"mimikatz.exe","FilePath":"\\\\Device\\\\HarddiskVolume3\\\\Users\\\\jsmith\\\\AppData\\\\Local\\\\Temp\\\\","CommandLine":"mimikatz.exe \\"privilege::debug\\" \\"sekurlsa::logonpasswords\\" exit","SHA256String":"2926dcdbe38a6b5b23a3bdb5c6c8ad3c30e1a79e9a5e8e51e4a5f3b2f9d6c7e1","MD5String":"a52b9c7d4f8e61b3a04d7c8e9f1b2c3d","MachineDomain":"CORP","SensorId":"b3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8","LocalIP":"10.24.14.88","EventUUID":"e1f2a3b4-c5d6-e7f8-a9b0-c1d2e3f4a5b6"}}',
            "subtype": "detection_summary",
        },
        {
            "raw": '{"metadata":{"customerIDString":"a1b2c3d4e5f6g7h8i9j0","offset":1928402,"eventType":"AuthActivityAuditEvent","eventCreationTime":1723638402000,"version":"1.0"},"event":{"UserId":"jsmith@corp.example.com","UserIp":"10.24.14.88","OperationName":"userAuthenticate","ServiceName":"CrowdStrike Authentication","Success":true,"UTCTimestamp":1723638402}}',
            "subtype": "auth_activity",
        },
        {
            "raw": '{"metadata":{"customerIDString":"a1b2c3d4e5f6g7h8i9j0","offset":1928418,"eventType":"DetectionSummaryEvent","eventCreationTime":1723638510000,"version":"1.0"},"event":{"ProcessStartTime":1723638505,"ProcessId":7742,"ParentProcessId":4812,"ComputerName":"WS-FIN-0042","UserName":"CORP\\\\bwilliams","DetectName":"MaliciousPowerShell","DetectDescription":"PowerShell executed a base64-encoded download cradle.","Severity":3,"SeverityName":"Medium","Tactic":"Execution","TacticId":"TA0002","Technique":"Command and Scripting Interpreter","TechniqueId":"T1059","FileName":"powershell.exe","FilePath":"\\\\Device\\\\HarddiskVolume3\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\","CommandLine":"powershell.exe -nop -w hidden -enc SQBFAFgAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAA...","SHA256String":"9f914d42706fe215501044acd85a32d58aaef1419d404fddfa5d3b48f66ccd9f","SensorId":"c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9","LocalIP":"10.24.14.42","RemoteIP":"185.220.101.14","EventUUID":"f2a3b4c5-d6e7-f8a9-b0c1-d2e3f4a5b6c7"}}',
            "subtype": "detection_summary",
        },
    ],

    "generator_hints": {
        "module_name": "generate_crowdstrike_falcon",
        "function_name": "generate_crowdstrike_falcon_logs",
        "volume_category": "endpoint",
        "baseline_events_per_day": 150,
        "subtypes": ["detection_summary", "auth_activity", "user_activity", "incident_summary"],
        "subtype_weights": {"detection_summary": 60, "user_activity": 20, "auth_activity": 15, "incident_summary": 5},
        "severities": {"1": "Informational", "2": "Low", "3": "Medium", "4": "High", "5": "Critical"},
        "severity_weights": {"2": 40, "3": 35, "4": 20, "5": 5},
        "tactics": ["Initial Access", "Execution", "Persistence", "Privilege Escalation", "Defense Evasion", "Credential Access", "Discovery", "Lateral Movement", "Collection", "Command and Control", "Exfiltration", "Impact"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://www.crowdstrike.com/blog/tech-center/streaming-api/", "kind": "vendor_doc", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://falcon.crowdstrike.com/documentation/page/streaming", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/4700", "kind": "splunkbase", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 87,
        "overall_confidence": 0.87,
    },
}
