"""Discovery spec for entraid_signin. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "entraid_signin",
        "display_name": "Microsoft Entra ID Sign-in",
        "vendor": "Microsoft",
        "product": "Entra ID (Azure AD)",
        "description": "Microsoft Entra ID (formerly Azure Active Directory) sign-in logs record interactive and non-interactive user authentication events, including application access, conditional access evaluation, MFA, and risk detection, emitted as JSON records through Azure Monitor diagnostic settings.",
    },

    "category": "cloud",
    "source_groups": ["cloud", "identity"],

    "format": {
        "type": "json",
        "confidence": 0.98,
        "delimiter": None,
        "kv_separator": None,
        "quoted_values": True,
        "timestamp_fields": ["time"],
        "timestamp_format": "ISO 8601 UTC (YYYY-MM-DDTHH:MM:SS.sssZ)",
    },

    "sourcetype": {
        "name": "azure:aad:signin",
        "confidence": 0.97,
        "origin": "Splunkbase TA (app 3757) — Splunk Add-on for Microsoft Cloud Services",
    },

    "fields": [
        # --- Envelope fields ---
        {"name": "time", "type": "string", "required": True, "example": "2026-04-12T14:22:17.123Z", "confidence": 1.0, "description": "Time at which the sign-in was recorded (UTC)"},
        {"name": "resourceId", "type": "string", "required": True, "example": "/tenants/11111111-2222-3333-4444-555555555555/providers/Microsoft.aadiam", "confidence": 1.0, "description": "Azure resource ID that emitted the log"},
        {"name": "operationName", "type": "string", "required": True, "example": "Sign-in activity", "confidence": 1.0, "description": "Name of the operation"},
        {"name": "operationVersion", "type": "string", "required": False, "example": "1.0", "confidence": 0.9, "description": "Version of the operation"},
        {"name": "category", "type": "string", "required": True, "example": "SignInLogs", "confidence": 1.0, "description": "Diagnostic log category: SignInLogs, NonInteractiveUserSignInLogs, ServicePrincipalSignInLogs, ManagedIdentitySignInLogs"},
        {"name": "tenantId", "type": "string", "required": True, "example": "11111111-2222-3333-4444-555555555555", "confidence": 1.0, "description": "Entra ID tenant ID"},
        {"name": "resultType", "type": "string", "required": True, "example": "0", "confidence": 1.0, "description": "Result code: 0 for success, otherwise the Entra ID error code"},
        {"name": "resultSignature", "type": "string", "required": False, "example": "None", "confidence": 0.8, "description": "Reserved field"},
        {"name": "resultDescription", "type": "string", "required": True, "example": "", "confidence": 1.0, "description": "Human-readable description of the result"},
        {"name": "durationMs", "type": "int", "required": False, "example": "0", "confidence": 0.7, "description": "Duration of the operation in milliseconds"},
        {"name": "callerIpAddress", "type": "ipv4", "required": False, "example": "203.0.113.24", "confidence": 0.9, "description": "IP address of the caller"},
        {"name": "correlationId", "type": "string", "required": True, "example": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "confidence": 1.0, "description": "Correlation ID grouping related events"},
        {"name": "identity", "type": "string", "required": False, "example": "Alice Example", "confidence": 0.8, "description": "Identity associated with the sign-in"},
        {"name": "Level", "type": "int", "required": False, "example": "4", "confidence": 0.8, "description": "Azure log level"},
        {"name": "location", "type": "string", "required": False, "example": "US", "confidence": 0.8, "description": "Two-letter country code of the caller"},

        # --- properties (nested) ---
        {"name": "properties.id", "type": "string", "required": True, "example": "11111111-aaaa-bbbb-cccc-222222222222", "confidence": 1.0, "description": "Unique sign-in event ID"},
        {"name": "properties.createdDateTime", "type": "string", "required": True, "example": "2026-04-12T14:22:17.123Z", "confidence": 1.0, "description": "Time the sign-in was created"},
        {"name": "properties.userDisplayName", "type": "string", "required": True, "example": "Alice Example", "confidence": 1.0, "description": "Display name of the user"},
        {"name": "properties.userPrincipalName", "type": "string", "required": True, "example": "alice@contoso.onmicrosoft.com", "confidence": 1.0, "description": "UPN of the user"},
        {"name": "properties.userId", "type": "string", "required": True, "example": "aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb", "confidence": 1.0, "description": "Object ID of the user"},
        {"name": "properties.appId", "type": "string", "required": True, "example": "00000003-0000-0ff1-ce00-000000000000", "confidence": 1.0, "description": "App ID of the target application"},
        {"name": "properties.appDisplayName", "type": "string", "required": True, "example": "Office 365 SharePoint Online", "confidence": 1.0, "description": "Display name of the target application"},
        {"name": "properties.ipAddress", "type": "ipv4", "required": True, "example": "203.0.113.24", "confidence": 1.0, "description": "IP address from which the sign-in originated"},
        {"name": "properties.clientAppUsed", "type": "string", "required": True, "example": "Browser", "confidence": 1.0, "description": "Client app used: Browser, Mobile Apps and Desktop clients, IMAP, POP, etc."},
        {"name": "properties.deviceDetail.deviceId", "type": "string", "required": False, "example": "cccccccc-1111-2222-3333-dddddddddddd", "confidence": 0.8, "description": "Device ID from Entra ID"},
        {"name": "properties.deviceDetail.displayName", "type": "string", "required": False, "example": "ALICE-LAPTOP", "confidence": 0.8, "description": "Device display name"},
        {"name": "properties.deviceDetail.operatingSystem", "type": "string", "required": False, "example": "Windows 11", "confidence": 0.9, "description": "Device operating system"},
        {"name": "properties.deviceDetail.browser", "type": "string", "required": False, "example": "Edge 122.0", "confidence": 0.9, "description": "Browser and version"},
        {"name": "properties.deviceDetail.isCompliant", "type": "bool", "required": False, "example": "true", "confidence": 0.8, "description": "Whether the device is marked compliant"},
        {"name": "properties.deviceDetail.isManaged", "type": "bool", "required": False, "example": "true", "confidence": 0.8, "description": "Whether the device is managed"},
        {"name": "properties.deviceDetail.trustType", "type": "string", "required": False, "example": "Azure AD joined", "confidence": 0.8, "description": "Trust type of the device"},
        {"name": "properties.location.city", "type": "string", "required": False, "example": "Redmond", "confidence": 0.8, "description": "City derived from the IP address"},
        {"name": "properties.location.state", "type": "string", "required": False, "example": "Washington", "confidence": 0.8, "description": "State or region derived from the IP address"},
        {"name": "properties.location.countryOrRegion", "type": "string", "required": False, "example": "US", "confidence": 0.9, "description": "Country or region code derived from the IP address"},
        {"name": "properties.status.errorCode", "type": "int", "required": True, "example": "0", "confidence": 1.0, "description": "Sign-in error code (0 = success)"},
        {"name": "properties.status.failureReason", "type": "string", "required": False, "example": "Other.", "confidence": 0.8, "description": "Reason for sign-in failure"},
        {"name": "properties.status.additionalDetails", "type": "string", "required": False, "example": "MFA requirement satisfied by claim in the token", "confidence": 0.7, "description": "Additional details about the sign-in result"},
        {"name": "properties.authenticationRequirement", "type": "string", "required": False, "example": "multiFactorAuthentication", "confidence": 0.9, "description": "Authentication requirement: singleFactorAuthentication, multiFactorAuthentication"},
        {"name": "properties.riskState", "type": "string", "required": False, "example": "none", "confidence": 0.9, "description": "Risk state: none, confirmedSafe, remediated, dismissed, atRisk, confirmedCompromised"},
        {"name": "properties.riskLevelAggregated", "type": "string", "required": False, "example": "none", "confidence": 0.9, "description": "Aggregated risk level: none, low, medium, high, hidden"},
        {"name": "properties.riskDetail", "type": "string", "required": False, "example": "none", "confidence": 0.9, "description": "Risk detail"},
        {"name": "properties.conditionalAccessStatus", "type": "string", "required": False, "example": "success", "confidence": 0.9, "description": "Result of conditional access evaluation: success, failure, notApplied, unknownFutureValue"},
        {"name": "properties.isInteractive", "type": "bool", "required": False, "example": "true", "confidence": 0.9, "description": "Whether the sign-in was interactive"},
        {"name": "properties.mfaDetail.authMethod", "type": "string", "required": False, "example": "Mobile app notification", "confidence": 0.8, "description": "MFA authentication method"},
        {"name": "properties.mfaDetail.authDetail", "type": "string", "required": False, "example": "Approved", "confidence": 0.7, "description": "MFA detail"},
    ],

    "sample_events": [
        {
            "raw": '{"time":"2026-04-12T14:22:17.123Z","resourceId":"/tenants/11111111-2222-3333-4444-555555555555/providers/Microsoft.aadiam","operationName":"Sign-in activity","operationVersion":"1.0","category":"SignInLogs","tenantId":"11111111-2222-3333-4444-555555555555","resultType":"0","resultSignature":"None","resultDescription":"","durationMs":0,"callerIpAddress":"203.0.113.24","correlationId":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee","identity":"Alice Example","Level":4,"location":"US","properties":{"id":"11111111-aaaa-bbbb-cccc-222222222222","createdDateTime":"2026-04-12T14:22:17.123Z","userDisplayName":"Alice Example","userPrincipalName":"alice@contoso.onmicrosoft.com","userId":"aaaaaaaa-1111-2222-3333-bbbbbbbbbbbb","appId":"00000003-0000-0ff1-ce00-000000000000","appDisplayName":"Office 365 SharePoint Online","ipAddress":"203.0.113.24","clientAppUsed":"Browser","isInteractive":true,"authenticationRequirement":"multiFactorAuthentication","conditionalAccessStatus":"success","riskState":"none","riskLevelAggregated":"none","riskDetail":"none","deviceDetail":{"deviceId":"cccccccc-1111-2222-3333-dddddddddddd","displayName":"ALICE-LAPTOP","operatingSystem":"Windows 11","browser":"Edge 122.0","isCompliant":true,"isManaged":true,"trustType":"Azure AD joined"},"location":{"city":"Redmond","state":"Washington","countryOrRegion":"US"},"status":{"errorCode":0,"failureReason":"Other.","additionalDetails":"MFA requirement satisfied by claim in the token"},"mfaDetail":{"authMethod":"Mobile app notification","authDetail":"Approved"}}}',
            "subtype": "interactive_success",
        },
        {
            "raw": '{"time":"2026-04-12T15:07:44.987Z","resourceId":"/tenants/11111111-2222-3333-4444-555555555555/providers/Microsoft.aadiam","operationName":"Sign-in activity","category":"SignInLogs","tenantId":"11111111-2222-3333-4444-555555555555","resultType":"50126","resultDescription":"Invalid username or password or Invalid on-premises username or password.","callerIpAddress":"198.51.100.88","correlationId":"ffffffff-aaaa-bbbb-cccc-111111111111","identity":"Bob Example","Level":4,"location":"NL","properties":{"id":"22222222-bbbb-cccc-dddd-333333333333","createdDateTime":"2026-04-12T15:07:44.987Z","userDisplayName":"Bob Example","userPrincipalName":"bob@contoso.onmicrosoft.com","userId":"bbbbbbbb-2222-3333-4444-cccccccccccc","appId":"1b730954-1685-4b74-9bfd-dac224a7b894","appDisplayName":"Azure Active Directory PowerShell","ipAddress":"198.51.100.88","clientAppUsed":"Mobile Apps and Desktop clients","isInteractive":false,"authenticationRequirement":"singleFactorAuthentication","conditionalAccessStatus":"notApplied","riskState":"atRisk","riskLevelAggregated":"medium","riskDetail":"none","deviceDetail":{"operatingSystem":"Linux","browser":"Other"},"location":{"city":"Amsterdam","state":"North Holland","countryOrRegion":"NL"},"status":{"errorCode":50126,"failureReason":"Invalid username or password or Invalid on-premises username or password."}}}',
            "subtype": "non_interactive_failure",
        },
    ],

    "generator_hints": {
        "module_name": "generate_entraid_signin",
        "function_name": "generate_entraid_signin_logs",
        "volume_category": "identity",
        "baseline_events_per_day": 1500,
        "subtypes": ["interactive_success", "interactive_failure", "non_interactive_success", "non_interactive_failure", "risky_signin", "mfa_challenge"],
        "subtype_weights": {"interactive_success": 55, "non_interactive_success": 25, "interactive_failure": 8, "non_interactive_failure": 5, "mfa_challenge": 5, "risky_signin": 2},
        "apps": ["Office 365 SharePoint Online", "Microsoft Teams", "Microsoft Exchange Online", "Azure Portal", "Microsoft Graph", "Microsoft Authenticator", "Outlook Web App"],
        "client_apps": ["Browser", "Mobile Apps and Desktop clients", "Exchange ActiveSync", "IMAP", "POP"],
        "result_codes": {"0": "Success", "50126": "Invalid credentials", "50053": "Account locked", "50055": "Password expired", "50158": "External challenge not satisfied", "53003": "Conditional access block"},
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://learn.microsoft.com/en-us/entra/identity/monitoring-health/concept-sign-ins", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/signinlogs", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/3757", "kind": "splunkbase", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 2,
        "research_mode": "full",
        "elapsed_sec": 90,
        "overall_confidence": 0.94,
    },
}
