"""Discovery spec for gcp_audit. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "gcp_audit",
        "display_name": "Google Cloud Platform Audit",
        "vendor": "Google",
        "product": "Google Cloud Platform",
        "description": "GCP Cloud Audit Logs record administrative and data access activity across Google Cloud services. Logs are emitted as structured LogEntry JSON objects with a protoPayload containing AuditLog details about who did what, where, and when.",
    },

    "category": "cloud",
    "source_groups": ["cloud"],

    "format": {
        "type": "json",
        "confidence": 0.98,
        "delimiter": None,
        "kv_separator": None,
        "quoted_values": True,
        "timestamp_fields": ["timestamp", "receiveTimestamp"],
        "timestamp_format": "ISO 8601 UTC (YYYY-MM-DDTHH:MM:SS.sssZ)",
    },

    "sourcetype": {
        "name": "google:gcp:pubsub:audit",
        "confidence": 0.97,
        "origin": "Splunkbase TA (app 3088) — Splunk Add-on for Google Cloud Platform",
    },

    "fields": [
        # --- LogEntry envelope ---
        {"name": "insertId", "type": "string", "required": True, "example": "abcd1234efgh5678", "confidence": 1.0, "description": "Unique identifier for the log entry"},
        {"name": "logName", "type": "string", "required": True, "example": "projects/example-project/logs/cloudaudit.googleapis.com%2Factivity", "confidence": 1.0, "description": "Log name including project and log type"},
        {"name": "timestamp", "type": "string", "required": True, "example": "2026-04-12T14:22:17.123456Z", "confidence": 1.0, "description": "Time the event occurred"},
        {"name": "receiveTimestamp", "type": "string", "required": True, "example": "2026-04-12T14:22:18.456789Z", "confidence": 1.0, "description": "Time the log entry was received by Cloud Logging"},
        {"name": "severity", "type": "string", "required": False, "example": "NOTICE", "confidence": 0.9, "description": "Severity level: DEFAULT, DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY"},
        {"name": "operation.id", "type": "string", "required": False, "example": "operation-1712931737-abcdef123456", "confidence": 0.8, "description": "Operation identifier"},
        {"name": "operation.producer", "type": "string", "required": False, "example": "compute.googleapis.com", "confidence": 0.8, "description": "Operation producer"},

        # --- Resource (nested) ---
        {"name": "resource.type", "type": "string", "required": True, "example": "gce_instance", "confidence": 1.0, "description": "Resource type: gce_instance, gcs_bucket, bigquery_dataset, k8s_cluster, iam_role, etc."},
        {"name": "resource.labels.project_id", "type": "string", "required": True, "example": "example-project", "confidence": 1.0, "description": "GCP project ID"},
        {"name": "resource.labels.instance_id", "type": "string", "required": False, "example": "1234567890123456789", "confidence": 0.8, "description": "Resource-specific label (e.g. GCE instance ID)"},
        {"name": "resource.labels.zone", "type": "string", "required": False, "example": "us-central1-a", "confidence": 0.8, "description": "Resource zone or region"},
        {"name": "resource.labels.location", "type": "string", "required": False, "example": "us-central1", "confidence": 0.8, "description": "Resource location"},

        # --- protoPayload (AuditLog) ---
        {"name": "protoPayload.@type", "type": "string", "required": True, "example": "type.googleapis.com/google.cloud.audit.AuditLog", "confidence": 1.0, "description": "Always type.googleapis.com/google.cloud.audit.AuditLog for audit events"},
        {"name": "protoPayload.serviceName", "type": "string", "required": True, "example": "compute.googleapis.com", "confidence": 1.0, "description": "Google Cloud service that produced the log"},
        {"name": "protoPayload.methodName", "type": "string", "required": True, "example": "v1.compute.instances.insert", "confidence": 1.0, "description": "Name of the service method or operation"},
        {"name": "protoPayload.resourceName", "type": "string", "required": True, "example": "projects/example-project/zones/us-central1-a/instances/web-server-01", "confidence": 1.0, "description": "Full resource name that identifies the resource targeted by the operation"},
        {"name": "protoPayload.authenticationInfo.principalEmail", "type": "string", "required": True, "example": "alice@example.com", "confidence": 1.0, "description": "Email address of the authenticated principal"},
        {"name": "protoPayload.authenticationInfo.principalSubject", "type": "string", "required": False, "example": "user:alice@example.com", "confidence": 0.8, "description": "Subject of the principal"},
        {"name": "protoPayload.authenticationInfo.serviceAccountKeyName", "type": "string", "required": False, "example": "//iam.googleapis.com/projects/example-project/serviceAccounts/sa@example-project.iam.gserviceaccount.com/keys/abcdef", "confidence": 0.7, "description": "Service account key used to authenticate"},
        {"name": "protoPayload.authorizationInfo", "type": "json", "required": False, "example": '[{"resource":"projects/example-project/zones/us-central1-a/instances/web-server-01","permission":"compute.instances.create","granted":true}]', "confidence": 0.9, "description": "Authorization information with permission checks"},
        {"name": "protoPayload.requestMetadata.callerIp", "type": "ipv4", "required": True, "example": "203.0.113.24", "confidence": 1.0, "description": "IP address of the caller"},
        {"name": "protoPayload.requestMetadata.callerSuppliedUserAgent", "type": "string", "required": False, "example": "google-cloud-sdk/466.0.0 command/gcloud.compute.instances.create", "confidence": 0.9, "description": "User agent supplied by the caller"},
        {"name": "protoPayload.requestMetadata.requestAttributes.time", "type": "string", "required": False, "example": "2026-04-12T14:22:17.123Z", "confidence": 0.8, "description": "Time when the request was processed"},
        {"name": "protoPayload.requestMetadata.requestAttributes.auth.principal", "type": "string", "required": False, "example": "user:alice@example.com", "confidence": 0.7, "description": "Authenticated principal of the request"},
        {"name": "protoPayload.status.code", "type": "int", "required": False, "example": "0", "confidence": 0.9, "description": "gRPC status code (0 = OK)"},
        {"name": "protoPayload.status.message", "type": "string", "required": False, "example": "", "confidence": 0.8, "description": "Status message"},
        {"name": "protoPayload.request.@type", "type": "string", "required": False, "example": "type.googleapis.com/compute.instances.insert", "confidence": 0.8, "description": "Type of the request payload"},
        {"name": "protoPayload.response.@type", "type": "string", "required": False, "example": "type.googleapis.com/operation", "confidence": 0.8, "description": "Type of the response payload"},
        {"name": "protoPayload.resourceLocation.currentLocations", "type": "json", "required": False, "example": '["us-central1-a"]', "confidence": 0.7, "description": "Current resource locations"},
    ],

    "sample_events": [
        {
            "raw": '{"insertId":"abcd1234efgh5678","logName":"projects/example-project/logs/cloudaudit.googleapis.com%2Factivity","timestamp":"2026-04-12T14:22:17.123456Z","receiveTimestamp":"2026-04-12T14:22:18.456789Z","severity":"NOTICE","resource":{"type":"gce_instance","labels":{"project_id":"example-project","instance_id":"1234567890123456789","zone":"us-central1-a"}},"protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","serviceName":"compute.googleapis.com","methodName":"v1.compute.instances.insert","resourceName":"projects/example-project/zones/us-central1-a/instances/web-server-01","authenticationInfo":{"principalEmail":"alice@example.com","principalSubject":"user:alice@example.com"},"authorizationInfo":[{"resource":"projects/example-project/zones/us-central1-a/instances/web-server-01","permission":"compute.instances.create","granted":true}],"requestMetadata":{"callerIp":"203.0.113.24","callerSuppliedUserAgent":"google-cloud-sdk/466.0.0 command/gcloud.compute.instances.create"},"status":{"code":0},"request":{"@type":"type.googleapis.com/compute.instances.insert"},"response":{"@type":"type.googleapis.com/operation"}}}',
            "subtype": "admin_activity",
        },
        {
            "raw": '{"insertId":"zyxw9876vuts5432","logName":"projects/example-project/logs/cloudaudit.googleapis.com%2Fdata_access","timestamp":"2026-04-12T15:04:30.987654Z","receiveTimestamp":"2026-04-12T15:04:31.112233Z","severity":"INFO","resource":{"type":"gcs_bucket","labels":{"project_id":"example-project","bucket_name":"example-bucket","location":"us"}},"protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","serviceName":"storage.googleapis.com","methodName":"storage.objects.get","resourceName":"projects/_/buckets/example-bucket/objects/reports/q1.pdf","authenticationInfo":{"principalEmail":"bob@example.com"},"authorizationInfo":[{"resource":"projects/_/buckets/example-bucket/objects/reports/q1.pdf","permission":"storage.objects.get","granted":true}],"requestMetadata":{"callerIp":"198.51.100.7","callerSuppliedUserAgent":"gsutil/5.27 (darwin) analytics/disabled"},"status":{"code":0}}}',
            "subtype": "data_access",
        },
        {
            "raw": '{"insertId":"errr1111aaaa2222","logName":"projects/example-project/logs/cloudaudit.googleapis.com%2Factivity","timestamp":"2026-04-12T15:22:10.500000Z","receiveTimestamp":"2026-04-12T15:22:11.000000Z","severity":"ERROR","resource":{"type":"iam_role","labels":{"project_id":"example-project"}},"protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","serviceName":"iam.googleapis.com","methodName":"google.iam.admin.v1.CreateRole","resourceName":"projects/example-project/roles/customRole","authenticationInfo":{"principalEmail":"eve@example.com"},"authorizationInfo":[{"resource":"projects/example-project","permission":"iam.roles.create","granted":false}],"requestMetadata":{"callerIp":"192.0.2.55","callerSuppliedUserAgent":"google-cloud-sdk/466.0.0"},"status":{"code":7,"message":"Permission denied on resource project example-project."}}}',
            "subtype": "denied",
        },
    ],

    "generator_hints": {
        "module_name": "generate_gcp_audit",
        "function_name": "generate_gcp_audit_logs",
        "volume_category": "cloud_audit",
        "baseline_events_per_day": 1800,
        "subtypes": ["admin_activity", "data_access", "system_event", "policy_denied", "denied"],
        "subtype_weights": {"admin_activity": 35, "data_access": 45, "system_event": 10, "policy_denied": 5, "denied": 5},
        "services": ["compute.googleapis.com", "storage.googleapis.com", "bigquery.googleapis.com", "iam.googleapis.com", "container.googleapis.com", "cloudkms.googleapis.com", "pubsub.googleapis.com", "cloudfunctions.googleapis.com"],
        "resource_types": ["gce_instance", "gcs_bucket", "bigquery_dataset", "k8s_cluster", "iam_role", "service_account", "cloud_function"],
        "regions": ["us-central1", "us-east1", "us-west1", "europe-west1", "europe-west4", "asia-southeast1", "asia-northeast1"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://cloud.google.com/logging/docs/audit", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://cloud.google.com/logging/docs/reference/audit/auditlog/rest/Shared.Types/AuditLog", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/3088", "kind": "splunkbase", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 85,
        "overall_confidence": 0.94,
    },
}
