"""Discovery spec for nginx_access. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "nginx_access",
        "display_name": "Nginx Access Log",
        "vendor": "F5/Nginx",
        "product": "Nginx",
        "description": "Nginx access log using the default combined log format — records each HTTP request with client address, timestamp, request line, status, response size, referer, user-agent, and forwarded-for header.",
    },

    "category": "web",
    "source_groups": ["web"],

    "format": {
        "type": "delimited",
        "confidence": 0.95,
        "delimiter": " ",
        "kv_separator": None,
        "quoted_values": True,
        "timestamp_fields": ["time_local"],
        "timestamp_format": "[DD/Mon/YYYY:HH:MM:SS +ZZZZ]",
    },

    "sourcetype": {
        "name": "nginx:plus:access",
        "confidence": 0.95,
        "origin": "Splunkbase TA (app 3258) — Splunk Add-on for Nginx",
    },

    "fields": [
        {"name": "remote_addr", "type": "ipv4", "required": True, "example": "203.0.113.5", "confidence": 1.0, "description": "Client IP address ($remote_addr)"},
        {"name": "remote_user", "type": "string", "required": True, "example": "-", "confidence": 1.0, "description": "Authenticated user from HTTP basic auth ($remote_user), '-' if none"},
        {"name": "time_local", "type": "string", "required": True, "example": "[12/Apr/2026:14:03:17 +0000]", "confidence": 1.0, "description": "Local time of request in common log format ($time_local)"},
        {"name": "request", "type": "string", "required": True, "example": "GET /api/users/42 HTTP/1.1", "confidence": 1.0, "description": "Full request line: method, URI, protocol ($request)"},
        {"name": "method", "type": "string", "required": True, "example": "GET", "confidence": 0.9, "description": "HTTP method extracted from request line"},
        {"name": "uri", "type": "string", "required": True, "example": "/api/users/42", "confidence": 0.9, "description": "Request URI extracted from request line"},
        {"name": "status", "type": "int", "required": True, "example": "200", "confidence": 1.0, "description": "HTTP status code returned to client ($status)"},
        {"name": "body_bytes_sent", "type": "int", "required": True, "example": "1532", "confidence": 1.0, "description": "Bytes of response body sent to client ($body_bytes_sent)"},
        {"name": "http_referer", "type": "string", "required": True, "example": "https://app.example.com/dashboard", "confidence": 1.0, "description": "Referer header ($http_referer), '-' if not present"},
        {"name": "http_user_agent", "type": "string", "required": True, "example": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "confidence": 1.0, "description": "User-Agent header ($http_user_agent)"},
        {"name": "http_x_forwarded_for", "type": "string", "required": True, "example": "-", "confidence": 1.0, "description": "X-Forwarded-For header ($http_x_forwarded_for), '-' if request did not traverse a proxy"},
        {"name": "request_time", "type": "float", "required": False, "example": "0.023", "confidence": 0.5, "description": "Request processing time in seconds ($request_time) — only when enabled"},
        {"name": "upstream_response_time", "type": "float", "required": False, "example": "0.019", "confidence": 0.5, "description": "Upstream response time ($upstream_response_time) — only when proxying"},
    ],

    "sample_events": [
        {
            "raw": '203.0.113.5 - - [12/Apr/2026:14:03:17 +0000] "GET /api/users/42 HTTP/1.1" 200 1532 "https://app.example.com/dashboard" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"',
            "subtype": "GET_200",
        },
        {
            "raw": '198.51.100.77 - admin [12/Apr/2026:14:04:02 +0000] "POST /login HTTP/2.0" 302 0 "https://app.example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "203.0.113.200"',
            "subtype": "POST_302",
        },
        {
            "raw": '192.0.2.14 - - [12/Apr/2026:14:04:55 +0000] "GET /wp-login.php HTTP/1.1" 404 162 "-" "Go-http-client/1.1" "-"',
            "subtype": "GET_404",
        },
    ],

    "generator_hints": {
        "module_name": "generate_nginx_access",
        "function_name": "generate_nginx_access_logs",
        "volume_category": "web",
        "baseline_events_per_day": 8000,
        "methods": ["GET", "POST", "PUT", "DELETE", "HEAD", "OPTIONS"],
        "method_weights": {"GET": 78, "POST": 13, "HEAD": 4, "PUT": 2, "DELETE": 2, "OPTIONS": 1},
        "statuses": [200, 201, 204, 301, 302, 304, 400, 401, 403, 404, 499, 500, 502, 503, 504],
        "status_weights": {"200": 72, "304": 9, "302": 5, "404": 4, "301": 2, "500": 2, "502": 2, "403": 1, "401": 1, "499": 1, "201": 1},
        "protocols": ["HTTP/1.1", "HTTP/2.0"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://nginx.org/en/docs/http/ngx_http_log_module.html", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://docs.nginx.com/nginx/admin-guide/monitoring/logging/", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/3258", "kind": "splunkbase", "trust": 0.9, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 38,
        "overall_confidence": 0.93,
    },
}
