"""Discovery spec for servicenow_incident. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "servicenow_incident",
        "display_name": "ServiceNow Incident",
        "vendor": "ServiceNow",
        "product": "ServiceNow ITSM",
        "description": "ServiceNow ITSM incident records retrieved from the Table API (table=incident). Each record is a full incident document with identity, lifecycle timestamps, priority/impact/urgency, assignment, caller, category, and resolution fields. Ingested by the Splunk Add-on for ServiceNow as key-value events.",
    },

    "category": "itsm",
    "source_groups": ["itsm"],

    "format": {
        "type": "kv",
        "confidence": 0.9,
        "delimiter": " ",
        "kv_separator": "=",
        "quoted_values": True,
        "timestamp_fields": ["sys_created_on", "sys_updated_on", "opened_at"],
        "timestamp_format": "YYYY-MM-DD HH:MM:SS (UTC)",
    },

    "sourcetype": {
        "name": "snow:incident",
        "confidence": 0.98,
        "origin": "Splunkbase TA (app 1928) — Splunk Add-on for ServiceNow",
    },

    "fields": [
        # --- Identity ---
        {"name": "sys_id", "type": "string", "required": True, "example": "f12ca184735123002728660c4cf6a7e0", "confidence": 1.0, "description": "32-char GUID uniquely identifying the incident record"},
        {"name": "number", "type": "string", "required": True, "example": "INC0010045", "confidence": 1.0, "description": "Human-readable incident number (INC prefix + 7 digits)"},
        {"name": "sys_class_name", "type": "string", "required": True, "example": "incident", "confidence": 1.0, "description": "Table class name — always 'incident' for this source"},

        # --- Lifecycle timestamps ---
        {"name": "sys_created_on", "type": "string", "required": True, "example": "2026-04-12 08:14:22", "confidence": 1.0, "description": "Record creation timestamp (UTC)"},
        {"name": "sys_updated_on", "type": "string", "required": True, "example": "2026-04-12 10:47:05", "confidence": 1.0, "description": "Last update timestamp (UTC)"},
        {"name": "sys_created_by", "type": "string", "required": True, "example": "jsmith", "confidence": 1.0, "description": "User ID that created the record"},
        {"name": "sys_updated_by", "type": "string", "required": True, "example": "a.jones", "confidence": 1.0, "description": "User ID that last updated the record"},
        {"name": "opened_at", "type": "string", "required": True, "example": "2026-04-12 08:14:22", "confidence": 1.0, "description": "Time the incident was opened"},
        {"name": "opened_by", "type": "string", "required": True, "example": "jsmith", "confidence": 1.0, "description": "User who opened the incident"},
        {"name": "closed_at", "type": "string", "required": False, "example": "2026-04-12 11:02:18", "confidence": 0.6, "description": "Time the incident was closed (empty until closure)"},
        {"name": "closed_by", "type": "string", "required": False, "example": "a.jones", "confidence": 0.6, "description": "User who closed the incident"},
        {"name": "resolved_at", "type": "string", "required": False, "example": "2026-04-12 10:47:05", "confidence": 0.7, "description": "Time the incident was resolved"},
        {"name": "resolved_by", "type": "string", "required": False, "example": "a.jones", "confidence": 0.7, "description": "User who resolved the incident"},

        # --- Priority / impact / urgency ---
        {"name": "state", "type": "int", "required": True, "example": "6", "confidence": 1.0, "description": "Incident state: 1=New, 2=In Progress, 3=On Hold, 6=Resolved, 7=Closed, 8=Canceled"},
        {"name": "incident_state", "type": "int", "required": True, "example": "6", "confidence": 1.0, "description": "Same as state — explicit incident state field"},
        {"name": "priority", "type": "int", "required": True, "example": "3", "confidence": 1.0, "description": "Calculated priority: 1=Critical, 2=High, 3=Moderate, 4=Low, 5=Planning"},
        {"name": "urgency", "type": "int", "required": True, "example": "2", "confidence": 1.0, "description": "Urgency: 1=High, 2=Medium, 3=Low"},
        {"name": "impact", "type": "int", "required": True, "example": "2", "confidence": 1.0, "description": "Impact: 1=High, 2=Medium, 3=Low"},
        {"name": "severity", "type": "int", "required": False, "example": "3", "confidence": 0.7, "description": "Severity: 1=High, 2=Medium, 3=Low"},

        # --- Categorization ---
        {"name": "category", "type": "string", "required": True, "example": "network", "confidence": 1.0, "description": "Top-level incident category"},
        {"name": "subcategory", "type": "string", "required": False, "example": "vpn", "confidence": 0.8, "description": "Subcategory within the category"},
        {"name": "cmdb_ci", "type": "string", "required": False, "example": "PRODSRV042", "confidence": 0.7, "description": "Configuration item (CI) affected by the incident"},
        {"name": "business_service", "type": "string", "required": False, "example": "Corporate Email", "confidence": 0.6, "description": "Business service impacted"},

        # --- Description ---
        {"name": "short_description", "type": "string", "required": True, "example": "Users unable to connect to VPN", "confidence": 1.0, "description": "One-line incident summary"},
        {"name": "description", "type": "string", "required": False, "example": "Multiple users from the sales team are reporting VPN disconnects after ~5 minutes of idle time.", "confidence": 0.8, "description": "Full description of the incident"},

        # --- Caller / assignment ---
        {"name": "caller_id", "type": "string", "required": True, "example": "jsmith", "confidence": 1.0, "description": "User who reported the incident"},
        {"name": "contact_type", "type": "string", "required": False, "example": "self-service", "confidence": 0.7, "description": "How the incident was reported: phone, email, self-service, chat, walk-in"},
        {"name": "assigned_to", "type": "string", "required": False, "example": "a.jones", "confidence": 0.8, "description": "User currently assigned to the incident"},
        {"name": "assignment_group", "type": "string", "required": True, "example": "Network Operations", "confidence": 0.95, "description": "Assignment group handling the incident"},

        # --- Resolution ---
        {"name": "resolution_code", "type": "string", "required": False, "example": "Solved (Permanently)", "confidence": 0.7, "description": "Resolution code / close code"},
        {"name": "resolution_notes", "type": "string", "required": False, "example": "Restarted VPN concentrator; sessions stable since 10:30.", "confidence": 0.7, "description": "Free-text resolution notes"},
        {"name": "close_code", "type": "string", "required": False, "example": "Solved (Permanently)", "confidence": 0.7, "description": "Close code selected at closure"},
        {"name": "close_notes", "type": "string", "required": False, "example": "Confirmed with caller, closing.", "confidence": 0.7, "description": "Notes entered at close"},

        # --- Misc ---
        {"name": "reassignment_count", "type": "int", "required": False, "example": "1", "confidence": 0.6, "description": "Number of times the incident was reassigned"},
        {"name": "reopen_count", "type": "int", "required": False, "example": "0", "confidence": 0.6, "description": "Number of times the incident was reopened"},
        {"name": "made_sla", "type": "string", "required": False, "example": "true", "confidence": 0.6, "description": "Whether the incident met its SLA ('true'/'false')"},
        {"name": "active", "type": "string", "required": True, "example": "false", "confidence": 1.0, "description": "Whether the incident record is active ('true'/'false')"},
    ],

    "sample_events": [
        {
            "raw": 'sys_id="f12ca184735123002728660c4cf6a7e0" number="INC0010045" sys_class_name="incident" sys_created_on="2026-04-12 08:14:22" sys_updated_on="2026-04-12 10:47:05" sys_created_by="jsmith" sys_updated_by="a.jones" opened_at="2026-04-12 08:14:22" opened_by="jsmith" resolved_at="2026-04-12 10:47:05" resolved_by="a.jones" state=6 incident_state=6 priority=3 urgency=2 impact=2 category="network" subcategory="vpn" short_description="Users unable to connect to VPN" caller_id="jsmith" contact_type="self-service" assigned_to="a.jones" assignment_group="Network Operations" resolution_code="Solved (Permanently)" resolution_notes="Restarted VPN concentrator; sessions stable since 10:30." active="false"',
            "subtype": "resolved",
        },
        {
            "raw": 'sys_id="ab34cd56ef78901234567890abcdef012" number="INC0010051" sys_class_name="incident" sys_created_on="2026-04-12 09:02:11" sys_updated_on="2026-04-12 09:05:44" sys_created_by="m.patel" sys_updated_by="system" opened_at="2026-04-12 09:02:11" opened_by="m.patel" state=1 incident_state=1 priority=1 urgency=1 impact=1 category="software" subcategory="email" short_description="Exchange OWA returning 503 for all users" caller_id="m.patel" contact_type="phone" assignment_group="Messaging Team" active="true"',
            "subtype": "new_critical",
        },
        {
            "raw": 'sys_id="99aa88bb77cc66dd55ee44ff33221100" number="INC0010052" sys_class_name="incident" sys_created_on="2026-04-12 09:30:08" sys_updated_on="2026-04-12 09:45:12" sys_created_by="k.nguyen" sys_updated_by="b.lopez" opened_at="2026-04-12 09:30:08" opened_by="k.nguyen" state=2 incident_state=2 priority=4 urgency=3 impact=3 category="hardware" subcategory="printer" short_description="Printer on 3rd floor offline" caller_id="k.nguyen" contact_type="self-service" assigned_to="b.lopez" assignment_group="Desktop Support" reassignment_count=0 reopen_count=0 active="true"',
            "subtype": "in_progress",
        },
    ],

    "generator_hints": {
        "module_name": "generate_servicenow_incident",
        "function_name": "generate_servicenow_incident_logs",
        "volume_category": "itsm",
        "baseline_events_per_day": 150,
        "states": [1, 2, 3, 6, 7, 8],
        "state_weights": {"1": 15, "2": 25, "3": 5, "6": 30, "7": 23, "8": 2},
        "priorities": [1, 2, 3, 4, 5],
        "priority_weights": {"1": 3, "2": 12, "3": 45, "4": 30, "5": 10},
        "categories": ["hardware", "software", "network", "database", "inquiry", "security"],
        "category_weights": {"software": 30, "hardware": 20, "network": 20, "inquiry": 15, "database": 10, "security": 5},
        "contact_types": ["self-service", "phone", "email", "chat", "walk-in"],
        "assignment_groups": ["Service Desk", "Network Operations", "Desktop Support", "Messaging Team", "Database Team", "Security Operations", "Application Support"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://docs.servicenow.com/bundle/washingtondc-it-service-management/page/product/incident-management/reference/r_IncidentFields.html", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://developer.servicenow.com/dev.do#!/reference/api/washingtondc/rest/c_TableAPI", "kind": "vendor_doc", "trust": 0.9, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/1928", "kind": "splunkbase", "trust": 0.9, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 67,
        "overall_confidence": 0.9,
    },
}
