"""Discovery spec for apache_access. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "apache_access",
        "display_name": "Apache HTTP Server Access Log",
        "vendor": "Apache Software Foundation",
        "product": "Apache HTTP Server",
        "description": "Apache HTTP Server access log in NCSA combined log format — space-separated fields with quoted strings recording every HTTP request handled by the server (client IP, method, URI, status, bytes, referer, user-agent).",
    },

    "category": "web",
    "source_groups": ["web"],

    "format": {
        "type": "delimited",
        "confidence": 0.95,
        "delimiter": " ",
        "kv_separator": None,
        "quoted_values": True,
        "timestamp_fields": ["timestamp"],
        "timestamp_format": "[DD/Mon/YYYY:HH:MM:SS +ZZZZ]",
    },

    "sourcetype": {
        "name": "access_combined",
        "confidence": 1.0,
        "origin": "Splunk native sourcetype — works out of the box with default Apache combined log format",
    },

    "fields": [
        {"name": "clientip", "type": "ipv4", "required": True, "example": "203.0.113.42", "confidence": 1.0, "description": "Client IP address making the HTTP request"},
        {"name": "ident", "type": "string", "required": True, "example": "-", "confidence": 1.0, "description": "RFC 1413 identity of the client (typically '-')"},
        {"name": "user", "type": "string", "required": True, "example": "-", "confidence": 1.0, "description": "Authenticated user (HTTP basic auth) or '-' if unauthenticated"},
        {"name": "timestamp", "type": "string", "required": True, "example": "[12/Apr/2026:13:55:36 +0000]", "confidence": 1.0, "description": "Request timestamp in strftime format [%d/%b/%Y:%H:%M:%S %z]"},
        {"name": "method", "type": "string", "required": True, "example": "GET", "confidence": 1.0, "description": "HTTP method (GET, POST, PUT, DELETE, HEAD, OPTIONS, PATCH)"},
        {"name": "uri", "type": "string", "required": True, "example": "/index.html", "confidence": 1.0, "description": "Request URI path including query string"},
        {"name": "protocol", "type": "string", "required": True, "example": "HTTP/1.1", "confidence": 1.0, "description": "HTTP protocol version (HTTP/1.0, HTTP/1.1, HTTP/2.0)"},
        {"name": "status", "type": "int", "required": True, "example": "200", "confidence": 1.0, "description": "HTTP status code returned to the client"},
        {"name": "bytes", "type": "int", "required": True, "example": "2326", "confidence": 1.0, "description": "Size of the response body in bytes (excluding headers)"},
        {"name": "referer", "type": "string", "required": True, "example": "https://www.example.com/", "confidence": 1.0, "description": "HTTP Referer header — URL that linked to the requested resource"},
        {"name": "useragent", "type": "string", "required": True, "example": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "confidence": 1.0, "description": "User-Agent header from the client browser or HTTP client"},
        {"name": "vhost", "type": "string", "required": False, "example": "www.example.com", "confidence": 0.6, "description": "Virtual host name (only when LogFormat %v is enabled)"},
        {"name": "response_time", "type": "int", "required": False, "example": "1243", "confidence": 0.5, "description": "Request processing time in microseconds (%D) — only when configured"},
    ],

    "sample_events": [
        {
            "raw": '203.0.113.42 - - [12/Apr/2026:13:55:36 +0000] "GET /index.html HTTP/1.1" 200 2326 "https://www.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"',
            "subtype": "GET_200",
        },
        {
            "raw": '198.51.100.17 - jsmith [12/Apr/2026:13:56:02 +0000] "POST /api/v1/orders HTTP/1.1" 201 512 "https://shop.example.com/cart" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"',
            "subtype": "POST_201",
        },
        {
            "raw": '192.0.2.88 - - [12/Apr/2026:13:56:45 +0000] "GET /admin/config.php HTTP/1.1" 404 491 "-" "curl/8.4.0"',
            "subtype": "GET_404",
        },
    ],

    "generator_hints": {
        "module_name": "generate_apache_access",
        "function_name": "generate_apache_access_logs",
        "volume_category": "web",
        "baseline_events_per_day": 5000,
        "methods": ["GET", "POST", "PUT", "DELETE", "HEAD", "OPTIONS"],
        "method_weights": {"GET": 75, "POST": 15, "HEAD": 4, "PUT": 3, "DELETE": 2, "OPTIONS": 1},
        "statuses": [200, 201, 204, 301, 302, 304, 400, 401, 403, 404, 500, 502, 503],
        "status_weights": {"200": 70, "304": 10, "302": 5, "404": 5, "301": 3, "500": 2, "403": 2, "401": 1, "201": 1, "400": 1},
        "protocols": ["HTTP/1.1", "HTTP/2.0"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://httpd.apache.org/docs/current/logs.html", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://httpd.apache.org/docs/current/mod/mod_log_config.html", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://docs.splunk.com/Documentation/Splunk/latest/Data/Listofpretrainedsourcetypes", "kind": "splunk_doc", "trust": 0.9, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 42,
        "overall_confidence": 0.95,
    },
}
