"""Discovery spec for aws_guardduty. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "aws_guardduty",
        "display_name": "AWS GuardDuty",
        "vendor": "AWS",
        "product": "GuardDuty",
        "description": "AWS GuardDuty is a threat detection service that continuously monitors AWS accounts, workloads, and data for malicious activity. Findings are JSON documents that describe the detection, the affected resource, and the observed service activity.",
    },

    "category": "cloud",
    "source_groups": ["cloud", "security"],

    "format": {
        "type": "json",
        "confidence": 0.98,
        "delimiter": None,
        "kv_separator": None,
        "quoted_values": True,
        "timestamp_fields": ["createdAt", "updatedAt", "eventFirstSeen", "eventLastSeen"],
        "timestamp_format": "ISO 8601 UTC (YYYY-MM-DDTHH:MM:SS.sssZ)",
    },

    "sourcetype": {
        "name": "aws:cloudwatch:guardduty",
        "confidence": 0.98,
        "origin": "Splunkbase TA (app 1876) — Splunk Add-on for AWS",
    },

    "fields": [
        # --- Finding identifiers ---
        {"name": "schemaVersion", "type": "string", "required": True, "example": "2.0", "confidence": 1.0, "description": "Schema version of the finding"},
        {"name": "accountId", "type": "string", "required": True, "example": "123456789012", "confidence": 1.0, "description": "AWS account ID of the affected account"},
        {"name": "region", "type": "string", "required": True, "example": "us-east-1", "confidence": 1.0, "description": "AWS region where the finding was generated"},
        {"name": "partition", "type": "string", "required": True, "example": "aws", "confidence": 1.0, "description": "AWS partition: aws, aws-us-gov, aws-cn"},
        {"name": "id", "type": "string", "required": True, "example": "1ab2c3d4e5f67890abcdef1234567890", "confidence": 1.0, "description": "Unique identifier for the finding"},
        {"name": "arn", "type": "string", "required": True, "example": "arn:aws:guardduty:us-east-1:123456789012:detector/abc123/finding/1ab2c3d4e5f67890abcdef1234567890", "confidence": 1.0, "description": "ARN of the finding"},
        {"name": "type", "type": "string", "required": True, "example": "UnauthorizedAccess:EC2/SSHBruteForce", "confidence": 1.0, "description": "Finding type (ThreatPurpose:ResourceType/ThreatFamilyName.DetectionMechanism!Artifact)"},
        {"name": "severity", "type": "float", "required": True, "example": "5.0", "confidence": 1.0, "description": "Severity value (1.0-8.9: low 1.0-3.9, medium 4.0-6.9, high 7.0-8.9)"},
        {"name": "confidence", "type": "float", "required": False, "example": "8.0", "confidence": 0.8, "description": "Confidence score of the finding"},
        {"name": "title", "type": "string", "required": True, "example": "198.51.100.25 is performing SSH brute force attacks against i-0abcdef1234567890.", "confidence": 1.0, "description": "Short human-readable title for the finding"},
        {"name": "description", "type": "string", "required": True, "example": "198.51.100.25 is performing SSH brute force attacks against i-0abcdef1234567890. Brute force attacks are used to gain unauthorized access to your instance by guessing the SSH password.", "confidence": 1.0, "description": "Full description of the finding"},
        {"name": "createdAt", "type": "string", "required": True, "example": "2026-04-12T14:22:17.123Z", "confidence": 1.0, "description": "ISO 8601 time when the finding was first created"},
        {"name": "updatedAt", "type": "string", "required": True, "example": "2026-04-12T14:32:44.456Z", "confidence": 1.0, "description": "ISO 8601 time when the finding was last updated"},

        # --- Resource (nested) ---
        {"name": "resource.resourceType", "type": "string", "required": True, "example": "Instance", "confidence": 1.0, "description": "Type of resource: Instance, AccessKey, S3Bucket, EKSCluster, KubernetesCluster, RDSDBInstance, Lambda"},
        {"name": "resource.instanceDetails.instanceId", "type": "string", "required": False, "example": "i-0abcdef1234567890", "confidence": 0.9, "description": "EC2 instance ID"},
        {"name": "resource.instanceDetails.instanceType", "type": "string", "required": False, "example": "t3.medium", "confidence": 0.9, "description": "EC2 instance type"},
        {"name": "resource.instanceDetails.availabilityZone", "type": "string", "required": False, "example": "us-east-1a", "confidence": 0.9, "description": "Availability zone of the instance"},
        {"name": "resource.instanceDetails.imageId", "type": "string", "required": False, "example": "ami-0abcdef1234567890", "confidence": 0.9, "description": "AMI ID of the instance"},
        {"name": "resource.instanceDetails.platform", "type": "string", "required": False, "example": "Linux", "confidence": 0.8, "description": "Instance platform"},
        {"name": "resource.accessKeyDetails.accessKeyId", "type": "string", "required": False, "example": "AKIAEXAMPLE1234567890", "confidence": 0.8, "description": "Access key ID involved in the finding"},
        {"name": "resource.accessKeyDetails.principalId", "type": "string", "required": False, "example": "AIDAEXAMPLE1234567890", "confidence": 0.8, "description": "Principal ID of the access key"},
        {"name": "resource.accessKeyDetails.userType", "type": "string", "required": False, "example": "IAMUser", "confidence": 0.8, "description": "User type"},
        {"name": "resource.accessKeyDetails.userName", "type": "string", "required": False, "example": "alice", "confidence": 0.8, "description": "User name"},

        # --- Service (nested) ---
        {"name": "service.serviceName", "type": "string", "required": True, "example": "guardduty", "confidence": 1.0, "description": "Name of the AWS service that generated the finding"},
        {"name": "service.detectorId", "type": "string", "required": True, "example": "abc123def456ghi789jkl012mno345pq", "confidence": 1.0, "description": "ID of the GuardDuty detector that generated the finding"},
        {"name": "service.eventFirstSeen", "type": "string", "required": True, "example": "2026-04-12T14:22:17.000Z", "confidence": 1.0, "description": "First time the activity was observed"},
        {"name": "service.eventLastSeen", "type": "string", "required": True, "example": "2026-04-12T14:32:44.000Z", "confidence": 1.0, "description": "Most recent time the activity was observed"},
        {"name": "service.count", "type": "int", "required": True, "example": "17", "confidence": 1.0, "description": "Total count of the occurrences of this finding"},
        {"name": "service.archived", "type": "bool", "required": False, "example": "false", "confidence": 0.9, "description": "Whether the finding is archived"},
        {"name": "service.resourceRole", "type": "string", "required": False, "example": "TARGET", "confidence": 0.9, "description": "Role of the resource in the event: TARGET, ACTOR"},

        # --- Action (nested under service) ---
        {"name": "service.action.actionType", "type": "string", "required": True, "example": "NETWORK_CONNECTION", "confidence": 1.0, "description": "Type of action: NETWORK_CONNECTION, AWS_API_CALL, DNS_REQUEST, PORT_PROBE, KUBERNETES_API_CALL"},
        {"name": "service.action.networkConnectionAction.connectionDirection", "type": "string", "required": False, "example": "INBOUND", "confidence": 0.9, "description": "Connection direction: INBOUND, OUTBOUND, UNKNOWN"},
        {"name": "service.action.networkConnectionAction.protocol", "type": "string", "required": False, "example": "TCP", "confidence": 0.9, "description": "Protocol used in the network connection"},
        {"name": "service.action.networkConnectionAction.blocked", "type": "bool", "required": False, "example": "false", "confidence": 0.9, "description": "Whether the connection was blocked"},
        {"name": "service.action.networkConnectionAction.remoteIpDetails.ipAddressV4", "type": "ipv4", "required": False, "example": "198.51.100.25", "confidence": 0.9, "description": "Remote IPv4 address of the connection"},
        {"name": "service.action.networkConnectionAction.remoteIpDetails.country.countryName", "type": "string", "required": False, "example": "Russia", "confidence": 0.8, "description": "Country name of the remote IP"},
        {"name": "service.action.networkConnectionAction.remoteIpDetails.city.cityName", "type": "string", "required": False, "example": "Moscow", "confidence": 0.8, "description": "City name of the remote IP"},
        {"name": "service.action.networkConnectionAction.remoteIpDetails.organization.asn", "type": "string", "required": False, "example": "12345", "confidence": 0.8, "description": "ASN of the remote IP"},
        {"name": "service.action.networkConnectionAction.remoteIpDetails.organization.org", "type": "string", "required": False, "example": "Example ISP", "confidence": 0.8, "description": "Organization of the remote IP"},
        {"name": "service.action.networkConnectionAction.remotePortDetails.port", "type": "int", "required": False, "example": "48293", "confidence": 0.9, "description": "Remote port of the connection"},
        {"name": "service.action.networkConnectionAction.localPortDetails.port", "type": "int", "required": False, "example": "22", "confidence": 0.9, "description": "Local port of the connection"},
        {"name": "service.additionalInfo.threatListName", "type": "string", "required": False, "example": "ProofPoint", "confidence": 0.7, "description": "Threat list name matched, if any"},
    ],

    "sample_events": [
        {
            "raw": '{"schemaVersion":"2.0","accountId":"123456789012","region":"us-east-1","partition":"aws","id":"1ab2c3d4e5f67890abcdef1234567890","arn":"arn:aws:guardduty:us-east-1:123456789012:detector/abc123def456ghi789jkl012mno345pq/finding/1ab2c3d4e5f67890abcdef1234567890","type":"UnauthorizedAccess:EC2/SSHBruteForce","resource":{"resourceType":"Instance","instanceDetails":{"instanceId":"i-0abcdef1234567890","instanceType":"t3.medium","availabilityZone":"us-east-1a","imageId":"ami-0abcdef1234567890","platform":"Linux"}},"service":{"serviceName":"guardduty","detectorId":"abc123def456ghi789jkl012mno345pq","action":{"actionType":"NETWORK_CONNECTION","networkConnectionAction":{"connectionDirection":"INBOUND","protocol":"TCP","blocked":false,"remoteIpDetails":{"ipAddressV4":"198.51.100.25","country":{"countryName":"Russia"},"city":{"cityName":"Moscow"},"organization":{"asn":"12345","org":"Example ISP"}},"remotePortDetails":{"port":48293},"localPortDetails":{"port":22}}},"resourceRole":"TARGET","eventFirstSeen":"2026-04-12T14:22:17.000Z","eventLastSeen":"2026-04-12T14:32:44.000Z","archived":false,"count":17},"severity":5.0,"confidence":8.0,"createdAt":"2026-04-12T14:22:17.123Z","updatedAt":"2026-04-12T14:32:44.456Z","title":"198.51.100.25 is performing SSH brute force attacks against i-0abcdef1234567890.","description":"198.51.100.25 is performing SSH brute force attacks against i-0abcdef1234567890. Brute force attacks are used to gain unauthorized access to your instance by guessing the SSH password."}',
            "subtype": "ssh_brute_force",
        },
        {
            "raw": '{"schemaVersion":"2.0","accountId":"123456789012","region":"us-west-2","partition":"aws","id":"2bc3d4e5f67890abcdef1234567890ab","arn":"arn:aws:guardduty:us-west-2:123456789012:detector/abc123/finding/2bc3d4e5f67890abcdef1234567890ab","type":"Recon:IAMUser/UserPermissions","resource":{"resourceType":"AccessKey","accessKeyDetails":{"accessKeyId":"AKIAEXAMPLE1234567890","principalId":"AIDAEXAMPLE1234567890","userType":"IAMUser","userName":"alice"}},"service":{"serviceName":"guardduty","detectorId":"abc123def456ghi789jkl012mno345pq","action":{"actionType":"AWS_API_CALL"},"resourceRole":"TARGET","eventFirstSeen":"2026-04-12T15:01:00.000Z","eventLastSeen":"2026-04-12T15:05:30.000Z","archived":false,"count":42},"severity":2.0,"confidence":7.5,"createdAt":"2026-04-12T15:01:00.000Z","updatedAt":"2026-04-12T15:05:30.000Z","title":"Unusual IAM user permission reconnaissance activity by alice.","description":"An IAM principal enumerated permissions at an unusually high rate. This may indicate an attacker mapping out privileges."}',
            "subtype": "iam_recon",
        },
    ],

    "generator_hints": {
        "module_name": "generate_aws_guardduty",
        "function_name": "generate_aws_guardduty_logs",
        "volume_category": "cloud_security",
        "baseline_events_per_day": 20,
        "subtypes": ["ssh_brute_force", "iam_recon", "crypto_mining", "malicious_ip", "dns_exfiltration", "s3_policy_change"],
        "subtype_weights": {"ssh_brute_force": 25, "iam_recon": 20, "crypto_mining": 15, "malicious_ip": 20, "dns_exfiltration": 10, "s3_policy_change": 10},
        "finding_types": ["UnauthorizedAccess:EC2/SSHBruteForce", "UnauthorizedAccess:EC2/RDPBruteForce", "Recon:IAMUser/UserPermissions", "CryptoCurrency:EC2/BitcoinTool.B!DNS", "Trojan:EC2/DNSDataExfiltration", "Policy:S3/BucketAnonymousAccessGranted", "Backdoor:EC2/C&CActivity.B!DNS"],
        "severity_distribution": {"low": 50, "medium": 35, "high": 15},
        "regions": ["us-east-1", "us-west-2", "eu-west-1", "eu-central-1", "ap-southeast-1"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings.html", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_finding-types-active.html", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/1876", "kind": "splunkbase", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 2,
        "research_mode": "full",
        "elapsed_sec": 82,
        "overall_confidence": 0.94,
    },
}
