"""Discovery spec for fortigate. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "fortigate",
        "display_name": "FortiGate Traffic",
        "vendor": "Fortinet",
        "product": "FortiGate (FortiOS)",
        "description": "FortiGate NGFW traffic logs record network sessions (forward, local, sniffer, multicast) in key-value pair syslog format with rich policy, application, and geo-enrichment fields.",
    },

    "category": "network",
    "source_groups": ["network"],

    # Fortigate carries the device name in devname= per event.
    "host_field": "devname",

    "format": {
        "type": "kv",
        "confidence": 0.85,
        "delimiter": " ",
        "kv_separator": "=",
        "quoted_values": True,
        "timestamp_fields": ["date", "time", "eventtime"],
        "timestamp_format": "date=YYYY-MM-DD time=HH:MM:SS (combined), eventtime=epoch_nanoseconds",
    },

    "sourcetype": {
        "name": "fgt_traffic",
        "confidence": 0.95,
        "origin": "Splunkbase TA (app 2846) — Fortinet FortiGate Add-On for Splunk",
    },

    "fields": [
        # --- Core header fields (present in every traffic log) ---
        {"name": "date", "type": "string", "required": True, "example": "2019-05-10", "confidence": 1.0, "description": "Log date (YYYY-MM-DD)"},
        {"name": "time", "type": "string", "required": True, "example": "11:37:47", "confidence": 1.0, "description": "Log time (HH:MM:SS)"},
        {"name": "logid", "type": "string", "required": True, "example": "0000000013", "confidence": 1.0, "description": "Log ID identifying the specific log message type"},
        {"name": "type", "type": "string", "required": True, "example": "traffic", "confidence": 1.0, "description": "Log category — always 'traffic' for traffic logs"},
        {"name": "subtype", "type": "string", "required": True, "example": "forward", "confidence": 1.0, "description": "Traffic subtype: forward, local, multicast, sniffer"},
        {"name": "level", "type": "string", "required": True, "example": "notice", "confidence": 1.0, "description": "Severity level: emergency, alert, critical, error, warning, notice, information, debug"},
        {"name": "vd", "type": "string", "required": True, "example": "vdom1", "confidence": 1.0, "description": "Virtual domain (VDOM) name"},
        {"name": "eventtime", "type": "int", "required": True, "example": "1557513467369913239", "confidence": 1.0, "description": "High-precision epoch timestamp in nanoseconds"},

        # --- Source fields ---
        {"name": "srcip", "type": "ipv4", "required": True, "example": "10.1.100.11", "confidence": 1.0, "description": "Source IP address"},
        {"name": "srcport", "type": "int", "required": True, "example": "58012", "confidence": 1.0, "description": "Source TCP/UDP port number"},
        {"name": "srcintf", "type": "string", "required": True, "example": "port12", "confidence": 1.0, "description": "Source interface name"},
        {"name": "srcintfrole", "type": "string", "required": True, "example": "undefined", "confidence": 1.0, "description": "Source interface role (lan, wan, dmz, undefined)"},
        {"name": "srcname", "type": "string", "required": False, "example": "workstation-01", "confidence": 0.7, "description": "Source host name (if resolved)"},
        {"name": "srcuuid", "type": "string", "required": False, "example": "ae28f494-5735-51e9-f247-d1d2ce663f4b", "confidence": 0.7, "description": "Source policy object UUID"},
        {"name": "srccountry", "type": "string", "required": True, "example": "Reserved", "confidence": 1.0, "description": "Source country based on GeoIP"},
        {"name": "srcuser", "type": "string", "required": False, "example": "admin", "confidence": 0.7, "description": "Authenticated source username"},

        # --- Destination fields ---
        {"name": "dstip", "type": "ipv4", "required": True, "example": "23.59.154.35", "confidence": 1.0, "description": "Destination IP address"},
        {"name": "dstport", "type": "int", "required": True, "example": "80", "confidence": 1.0, "description": "Destination TCP/UDP port number"},
        {"name": "dstintf", "type": "string", "required": True, "example": "port11", "confidence": 1.0, "description": "Destination interface name"},
        {"name": "dstintfrole", "type": "string", "required": True, "example": "undefined", "confidence": 1.0, "description": "Destination interface role"},
        {"name": "dstname", "type": "string", "required": False, "example": "server-01", "confidence": 0.7, "description": "Destination host name (if resolved)"},
        {"name": "dstuuid", "type": "string", "required": False, "example": "ae28f494-5735-51e9-f247-d1d2ce663f4b", "confidence": 0.7, "description": "Destination policy object UUID"},
        {"name": "dstcountry", "type": "string", "required": True, "example": "Canada", "confidence": 1.0, "description": "Destination country based on GeoIP"},
        {"name": "dstuser", "type": "string", "required": False, "example": "", "confidence": 0.7, "description": "Destination username"},

        # --- Session and policy fields ---
        {"name": "poluuid", "type": "string", "required": False, "example": "ccb269e0-5735-51e9-a218-a397dd08b7eb", "confidence": 0.7, "description": "UUID of the matched policy"},
        {"name": "sessionid", "type": "int", "required": True, "example": "105048", "confidence": 1.0, "description": "Unique numeric session identifier"},
        {"name": "proto", "type": "int", "required": True, "example": "6", "confidence": 1.0, "description": "IP protocol number (6=TCP, 17=UDP, 1=ICMP)"},
        {"name": "action", "type": "string", "required": True, "example": "close", "confidence": 1.0, "description": "Disposition: accept, deny, close, server-rst, client-rst, timeout"},
        {"name": "policyid", "type": "int", "required": True, "example": "1", "confidence": 1.0, "description": "ID number of the matched firewall policy"},
        {"name": "policytype", "type": "string", "required": True, "example": "policy", "confidence": 1.0, "description": "Type of policy matched: policy, local-in-policy, sniffer"},
        {"name": "policymode", "type": "string", "required": False, "example": "flow", "confidence": 0.7, "description": "Policy mode: learn, flow, proxy"},
        {"name": "service", "type": "string", "required": True, "example": "HTTP", "confidence": 1.0, "description": "Application service name (HTTP, HTTPS, DNS, etc.)"},

        # --- NAT fields ---
        {"name": "trandisp", "type": "string", "required": True, "example": "snat", "confidence": 1.0, "description": "Translation disposition: snat, dnat, noop"},
        {"name": "transip", "type": "ipv4", "required": False, "example": "172.16.200.2", "confidence": 0.8, "description": "Translated source IP address (NAT)"},
        {"name": "transport", "type": "int", "required": False, "example": "0", "confidence": 0.7, "description": "Translated source port (NAT)"},

        # --- Application control fields ---
        {"name": "appid", "type": "int", "required": False, "example": "40568", "confidence": 0.7, "description": "Application ID matched by application control"},
        {"name": "app", "type": "string", "required": False, "example": "Web Management(HTTPS)", "confidence": 0.8, "description": "Application name matched by application control"},
        {"name": "appcat", "type": "string", "required": False, "example": "unscanned", "confidence": 0.8, "description": "Application category"},
        {"name": "apprisk", "type": "string", "required": False, "example": "medium", "confidence": 0.7, "description": "Application risk level: critical, high, medium, low, elevated"},

        # --- Byte/packet counters ---
        {"name": "duration", "type": "int", "required": False, "example": "5", "confidence": 0.8, "description": "Session duration in seconds"},
        {"name": "sentbyte", "type": "int", "required": False, "example": "1247", "confidence": 0.8, "description": "Bytes sent from source to destination"},
        {"name": "rcvdbyte", "type": "int", "required": False, "example": "1719", "confidence": 0.8, "description": "Bytes received from destination to source"},
        {"name": "sentpkt", "type": "int", "required": False, "example": "5", "confidence": 0.8, "description": "Packets sent from source to destination"},
        {"name": "rcvdpkt", "type": "int", "required": False, "example": "6", "confidence": 0.8, "description": "Packets received from destination to source"},
        {"name": "sentdelta", "type": "int", "required": False, "example": "0", "confidence": 0.7, "description": "Bytes sent since last log update (prolonged sessions)"},
        {"name": "rcvddelta", "type": "int", "required": False, "example": "0", "confidence": 0.7, "description": "Bytes received since last log update"},

        # --- UTM / threat fields ---
        {"name": "utmaction", "type": "string", "required": False, "example": "allow", "confidence": 0.7, "description": "UTM action applied: allow, block, monitor"},
        {"name": "countips", "type": "int", "required": False, "example": "1", "confidence": 0.7, "description": "Count of IPS events in the session"},
        {"name": "crscore", "type": "int", "required": False, "example": "5", "confidence": 0.7, "description": "Threat score from content rating"},
        {"name": "craction", "type": "int", "required": False, "example": "32768", "confidence": 0.7, "description": "Content rating action bitmask"},
        {"name": "utmref", "type": "string", "required": False, "example": "65162-7772", "confidence": 0.7, "description": "UTM reference ID linking to security log entries"},

        # --- Device fields ---
        {"name": "devname", "type": "string", "required": False, "example": "FGT60E", "confidence": 0.7, "description": "Device name of the FortiGate unit"},
        {"name": "devid", "type": "string", "required": False, "example": "FG100E0000000000", "confidence": 0.7, "description": "Serial number / device ID"},
    ],

    "sample_events": [
        {
            "raw": 'date=2019-05-10 time=11:37:47 logid="0000000013" type="traffic" subtype="forward" level="notice" vd="vdom1" eventtime=1557513467369913239 srcip=10.1.100.11 srcport=58012 srcintf="port12" srcintfrole="undefined" dstip=23.59.154.35 dstport=80 dstintf="port11" dstintfrole="undefined" srcuuid="ae28f494-5735-51e9-f247-d1d2ce663f4b" dstuuid="ae28f494-5735-51e9-f247-d1d2ce663f4b" poluuid="ccb269e0-5735-51e9-a218-a397dd08b7eb" sessionid=105048 proto=6 action="close" policyid=1 policytype="policy" service="HTTP" dstcountry="Canada" srccountry="Reserved" trandisp="snat" transip=172.16.200.2',
            "subtype": "forward",
        },
        {
            "raw": 'date=2019-05-10 time=11:50:48 logid="0001000014" type="traffic" subtype="local" level="notice" vd="vdom1" eventtime=1557514248379911176 srcip=172.16.200.254 srcport=62024 srcintf="port11" srcintfrole="undefined" dstip=172.16.200.2 dstport=443 dstintf="vdom1" dstintfrole="undefined" sessionid=107478 proto=6 action="server-rst" policyid=0 policytype="local-in-policy" service="HTTPS" dstcountry="Reserved" srccountry="Reserved" trandisp="noop" app="Web Management(HTTPS)" duration=5 sentbyte=1247 rcvdbyte=1719 sentpkt=5 rcvdpkt=6 appcat="unscanned"',
            "subtype": "local",
        },
        {
            "raw": 'date=2019-05-10 time=14:18:54 logid="0004000017" type="traffic" subtype="sniffer" level="notice" vd="root" eventtime=1557523134021045897 srcip=208.91.114.4 srcport=50463 srcintf="port1" srcintfrole="undefined" dstip=104.80.88.154 dstport=443 dstintf="port1" dstintfrole="undefined" sessionid=2193276 proto=6 action="accept" policyid=3 policytype="sniffer" service="HTTPS" dstcountry="United States" srccountry="Canada" trandisp="snat" transip=0.0.0.0 transport=0 duration=10 sentbyte=0 rcvdbyte=0 sentpkt=0 rcvdpkt=0 appcat="unscanned" utmaction="allow" countips=1 crscore=5 craction=32768 sentdelta=0 rcvddelta=0 utmref=65162-7772',
            "subtype": "sniffer",
        },
    ],

    "generator_hints": {
        "module_name": "generate_fortigate",
        "function_name": "generate_fortigate_logs",
        "volume_category": "firewall",
        "baseline_events_per_day": 500,
        "subtypes": ["forward", "local", "sniffer"],
        "subtype_weights": {"forward": 75, "local": 20, "sniffer": 5},
        "actions": ["accept", "deny", "close", "server-rst", "client-rst", "timeout"],
        "action_weights": {"accept": 40, "close": 35, "deny": 10, "server-rst": 5, "client-rst": 5, "timeout": 5},
        "services": ["HTTP", "HTTPS", "DNS", "SSH", "SMTP", "FTP", "IMAP", "POP3", "SMB", "RDP", "NTP", "SNMP"],
        "protocols": {"6": "TCP", "17": "UDP", "1": "ICMP"},
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://docs.fortinet.com/document/fortigate/7.6.4/fortios-log-message-reference/357866/log-message-fields", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://docs.fortinet.com/document/fortigate/6.2.0/cookbook/986892/sample-logs-by-log-type", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://docs.fortinet.com/document/fortigate/7.6.4/administration-guide/986892/sample-logs-by-log-type", "kind": "vendor_doc", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/2846", "kind": "splunkbase", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 89,
        "overall_confidence": 0.88,
    },
}
