"""Discovery spec for linux_auth. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "linux_auth",
        "display_name": "Linux Auth Log",
        "vendor": "Open Source",
        "product": "Linux syslog (auth.log / secure)",
        "description": "Linux authentication events from /var/log/auth.log (Debian/Ubuntu) or /var/log/secure (RHEL/CentOS). Captures SSH connection activity, sudo invocations, PAM session events, and su transitions in BSD syslog format.",
    },

    "category": "linux",
    "source_groups": ["linux", "endpoint"],

    "format": {
        "type": "syslog_bsd",
        "confidence": 0.95,
        "delimiter": " ",
        "kv_separator": None,
        "quoted_values": False,
        "timestamp_fields": ["timestamp"],
        "timestamp_format": "Mmm dd HH:MM:SS (BSD syslog header, no year)",
    },

    "sourcetype": {
        "name": "linux_secure",
        "confidence": 0.98,
        "origin": "Splunkbase TA (app 833) — Splunk Add-on for Unix and Linux",
    },

    "fields": [
        {"name": "timestamp", "type": "string", "required": True, "example": "Aug 14 09:23:41", "confidence": 1.0, "description": "BSD syslog header timestamp (Mmm dd HH:MM:SS)"},
        {"name": "host", "type": "string", "required": True, "example": "srv-web-01", "confidence": 1.0, "description": "Hostname of the system that generated the log"},
        {"name": "process", "type": "string", "required": True, "example": "sshd", "confidence": 1.0, "description": "Process name that emitted the event (sshd, sudo, su, login, CRON)"},
        {"name": "pid", "type": "int", "required": True, "example": "18342", "confidence": 1.0, "description": "Process ID of the emitting process"},
        {"name": "message", "type": "string", "required": True, "example": "Accepted password for jsmith from 10.24.14.88 port 49822 ssh2", "confidence": 1.0, "description": "Raw message body after the process[pid]: prefix"},
        {"name": "user", "type": "string", "required": False, "example": "jsmith", "confidence": 0.95, "description": "Authenticating or target user name (parsed from message)"},
        {"name": "src_ip", "type": "ipv4", "required": False, "example": "10.24.14.88", "confidence": 0.9, "description": "Source IP address for SSH connection attempts"},
        {"name": "src_port", "type": "int", "required": False, "example": "49822", "confidence": 0.9, "description": "Source TCP port for SSH connection attempts"},
        {"name": "ssh_auth_method", "type": "string", "required": False, "example": "password", "confidence": 0.9, "description": "SSH authentication method: password, publickey, keyboard-interactive, none"},
        {"name": "ssh_protocol", "type": "string", "required": False, "example": "ssh2", "confidence": 0.8, "description": "SSH protocol version"},
        {"name": "status", "type": "string", "required": False, "example": "success", "confidence": 0.9, "description": "Outcome of the auth attempt: success or failure"},
        {"name": "action", "type": "string", "required": False, "example": "Accepted", "confidence": 0.9, "description": "SSHD action verb: Accepted, Failed, Invalid, Disconnected"},
        {"name": "sudo_user", "type": "string", "required": False, "example": "jsmith", "confidence": 0.8, "description": "User who invoked sudo"},
        {"name": "sudo_tty", "type": "string", "required": False, "example": "pts/0", "confidence": 0.8, "description": "TTY from which sudo was invoked"},
        {"name": "sudo_pwd", "type": "string", "required": False, "example": "/home/jsmith", "confidence": 0.7, "description": "Working directory when sudo was invoked"},
        {"name": "sudo_target_user", "type": "string", "required": False, "example": "root", "confidence": 0.8, "description": "Target user sudo elevated to"},
        {"name": "sudo_command", "type": "string", "required": False, "example": "/usr/bin/apt update", "confidence": 0.9, "description": "Command executed via sudo"},
        {"name": "pam_module", "type": "string", "required": False, "example": "pam_unix", "confidence": 0.8, "description": "PAM module involved in the event"},
        {"name": "pam_session", "type": "string", "required": False, "example": "opened", "confidence": 0.8, "description": "PAM session state: opened or closed"},
        {"name": "invalid_user", "type": "bool", "required": False, "example": "false", "confidence": 0.7, "description": "True if the login attempt was for an invalid user"},
    ],

    "sample_events": [
        {
            "raw": "Aug 14 09:23:41 srv-web-01 sshd[18342]: Accepted password for jsmith from 10.24.14.88 port 49822 ssh2",
            "subtype": "ssh_accepted",
        },
        {
            "raw": "Aug 14 09:23:41 srv-web-01 sshd[18342]: pam_unix(sshd:session): session opened for user jsmith by (uid=0)",
            "subtype": "pam_session_open",
        },
        {
            "raw": "Aug 14 09:24:02 srv-web-01 sshd[18355]: Failed password for invalid user admin from 192.168.5.210 port 50122 ssh2",
            "subtype": "ssh_failed",
        },
        {
            "raw": "Aug 14 09:27:15 srv-web-01 sudo:  jsmith : TTY=pts/0 ; PWD=/home/jsmith ; USER=root ; COMMAND=/usr/bin/apt update",
            "subtype": "sudo_command",
        },
        {
            "raw": "Aug 14 09:31:48 srv-web-01 sshd[18342]: pam_unix(sshd:session): session closed for user jsmith",
            "subtype": "pam_session_close",
        },
    ],

    "generator_hints": {
        "module_name": "generate_linux_auth",
        "function_name": "generate_linux_auth_logs",
        "volume_category": "endpoint",
        "baseline_events_per_day": 800,
        "subtypes": ["ssh_accepted", "ssh_failed", "pam_session_open", "pam_session_close", "sudo_command", "su_switch", "invalid_user"],
        "subtype_weights": {"ssh_accepted": 25, "pam_session_open": 20, "pam_session_close": 20, "sudo_command": 15, "ssh_failed": 10, "invalid_user": 7, "su_switch": 3},
        "processes": ["sshd", "sudo", "su", "login", "CRON", "systemd-logind"],
        "ssh_auth_methods": ["password", "publickey", "keyboard-interactive"],
        "common_sudo_commands": ["/usr/bin/apt update", "/usr/bin/systemctl restart nginx", "/bin/cat /var/log/syslog", "/usr/bin/vim /etc/hosts", "/bin/su -"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://www.rsyslog.com/doc/configuration/templates.html", "kind": "vendor_doc", "trust": 0.85, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://man.openbsd.org/sshd", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://www.sudo.ws/docs/man/sudoers.man/", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/833", "kind": "splunkbase", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 5,
        "research_mode": "full",
        "elapsed_sec": 74,
        "overall_confidence": 0.92,
    },
}
