"""Discovery spec for mssql_errorlog. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "mssql_errorlog",
        "display_name": "Microsoft SQL Server Error Log",
        "vendor": "Microsoft",
        "product": "SQL Server",
        "description": "Microsoft SQL Server ERRORLOG file — plain-text log written by the SQL Server engine containing startup messages, login audit events, backup/restore events, and errors. Each line begins with a timestamp, source component, and optionally a SPID, followed by the message text.",
    },

    "category": "windows",
    "source_groups": ["windows", "database"],

    "format": {
        "type": "delimited",
        "confidence": 0.75,
        "delimiter": " ",
        "kv_separator": None,
        "quoted_values": False,
        "timestamp_fields": ["timestamp"],
        "timestamp_format": "YYYY-MM-DD HH:MM:SS.ff",
    },

    "sourcetype": {
        "name": "mssql:errorlog",
        "confidence": 0.9,
        "origin": "Splunkbase TA (app 2648) — Splunk Add-on for Microsoft SQL Server",
    },

    "fields": [
        {"name": "timestamp", "type": "string", "required": True, "example": "2026-04-12 14:22:07.83", "confidence": 1.0, "description": "Event timestamp in 'YYYY-MM-DD HH:MM:SS.ff' format (local time of SQL Server host)"},
        {"name": "source", "type": "string", "required": True, "example": "Logon", "confidence": 0.95, "description": "Source component writing the message: Server, Logon, spidN, Backup, etc."},
        {"name": "spid", "type": "string", "required": False, "example": "spid54", "confidence": 0.7, "description": "SQL Server process ID (session identifier) when event is associated with a session"},
        {"name": "severity", "type": "string", "required": False, "example": "Error: 18456, Severity: 14, State: 8.", "confidence": 0.6, "description": "Error number, severity level, and state (when the message is an error message)"},
        {"name": "error_number", "type": "int", "required": False, "example": "18456", "confidence": 0.6, "description": "SQL Server error number parsed from the severity line"},
        {"name": "severity_level", "type": "int", "required": False, "example": "14", "confidence": 0.6, "description": "SQL Server error severity (0-25)"},
        {"name": "message", "type": "string", "required": True, "example": "Login failed for user 'sa'. Reason: Password did not match that for the login provided.", "confidence": 1.0, "description": "Free-text message body describing the event"},
        {"name": "client_ip", "type": "ipv4", "required": False, "example": "203.0.113.77", "confidence": 0.5, "description": "Client IP address (extracted from login failure messages when present)"},
    ],

    "sample_events": [
        {
            "raw": "2026-04-12 14:22:07.83 Logon       Error: 18456, Severity: 14, State: 8.",
            "subtype": "login_failure_header",
        },
        {
            "raw": "2026-04-12 14:22:07.83 Logon       Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 203.0.113.77]",
            "subtype": "login_failure_detail",
        },
        {
            "raw": "2026-04-12 14:35:12.04 Backup      Database backed up. Database: AdventureWorks, creation date(time): 2024/01/15(09:12:33), pages dumped: 24568, first LSN: 120:456:37, last LSN: 120:480:1, number of dump devices: 1, device information: (FILE=1, TYPE=DISK: {'D:\\Backups\\AdventureWorks_full.bak'}). This is an informational message only. No user action is required.",
            "subtype": "backup_complete",
        },
    ],

    "generator_hints": {
        "module_name": "generate_mssql_errorlog",
        "function_name": "generate_mssql_errorlog_logs",
        "volume_category": "database",
        "baseline_events_per_day": 300,
        "sources": ["Server", "Logon", "Backup", "spid51", "spid52", "spid53", "spid54"],
        "source_weights": {"Logon": 40, "Server": 25, "Backup": 15, "spid51": 5, "spid52": 5, "spid53": 5, "spid54": 5},
        "event_types": ["login_success", "login_failure", "backup_complete", "startup", "shutdown", "deadlock", "config_change"],
        "event_type_weights": {"login_success": 50, "login_failure": 20, "backup_complete": 15, "startup": 3, "shutdown": 2, "deadlock": 5, "config_change": 5},
        "common_error_numbers": [18456, 18452, 17187, 17892, 1205, 823, 9002],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://learn.microsoft.com/en-us/sql/tools/configuration-manager/viewing-the-sql-server-error-log", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://learn.microsoft.com/en-us/sql/relational-databases/errors-events/mssqlserver-18456-database-engine-error", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/2648", "kind": "splunkbase", "trust": 0.9, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 44,
        "overall_confidence": 0.85,
    },
}
