"""Discovery spec for o365_management. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "o365_management",
        "display_name": "Microsoft 365 Management Activity",
        "vendor": "Microsoft",
        "product": "Microsoft 365",
        "description": "Microsoft 365 Management Activity API exposes tenant-wide audit events from Exchange Online, SharePoint Online, OneDrive for Business, Entra ID, Microsoft Teams, DLP, and other Microsoft 365 workloads as JSON records with a common schema plus workload-specific extensions.",
    },

    "category": "cloud",
    "source_groups": ["cloud", "saas"],

    "format": {
        "type": "json",
        "confidence": 0.98,
        "delimiter": None,
        "kv_separator": None,
        "quoted_values": True,
        "timestamp_fields": ["CreationTime"],
        "timestamp_format": "ISO 8601 UTC (YYYY-MM-DDTHH:MM:SS)",
    },

    "sourcetype": {
        "name": "o365:management:activity",
        "confidence": 0.97,
        "origin": "Splunkbase TA (app 4055) — Splunk Add-on for Microsoft Office 365",
    },

    "fields": [
        # --- Common schema (all workloads) ---
        {"name": "CreationTime", "type": "string", "required": True, "example": "2026-04-12T14:22:17", "confidence": 1.0, "description": "Date and time in UTC when the user performed the activity"},
        {"name": "Id", "type": "string", "required": True, "example": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "confidence": 1.0, "description": "GUID that uniquely identifies the audit record"},
        {"name": "Operation", "type": "string", "required": True, "example": "FileAccessed", "confidence": 1.0, "description": "Name of the user or admin activity"},
        {"name": "OrganizationId", "type": "string", "required": True, "example": "11111111-2222-3333-4444-555555555555", "confidence": 1.0, "description": "GUID of the Microsoft 365 tenant"},
        {"name": "RecordType", "type": "int", "required": True, "example": "6", "confidence": 1.0, "description": "Type of operation: 1=ExchangeAdmin, 2=ExchangeItem, 4=SharePointFileOperation, 6=SharePoint, 8=AzureActiveDirectory, 15=AzureActiveDirectoryStsLogon, 25=MicrosoftTeams, 28=ThreatIntelligence"},
        {"name": "ResultStatus", "type": "string", "required": True, "example": "Succeeded", "confidence": 1.0, "description": "Whether the action was successful: Succeeded, PartiallySucceeded, Failed"},
        {"name": "UserKey", "type": "string", "required": True, "example": "10033FFFA1234567", "confidence": 1.0, "description": "Alternative ID for the user identified in UserId"},
        {"name": "UserType", "type": "int", "required": True, "example": "0", "confidence": 1.0, "description": "Type of user: 0=Regular, 1=Reserved, 2=Admin, 3=DcAdmin, 4=System, 5=Application, 6=ServicePrincipal"},
        {"name": "Version", "type": "int", "required": True, "example": "1", "confidence": 1.0, "description": "Version number of the activity record"},
        {"name": "Workload", "type": "string", "required": True, "example": "SharePoint", "confidence": 1.0, "description": "Microsoft 365 service where the activity occurred: Exchange, SharePoint, OneDrive, AzureActiveDirectory, MicrosoftTeams, SecurityComplianceCenter, DLP, ThreatIntelligence"},
        {"name": "ClientIP", "type": "string", "required": True, "example": "203.0.113.24", "confidence": 1.0, "description": "IP address of the device used when the activity was logged"},
        {"name": "UserId", "type": "string", "required": True, "example": "alice@contoso.onmicrosoft.com", "confidence": 1.0, "description": "UPN of the user who performed the action"},
        {"name": "ObjectId", "type": "string", "required": False, "example": "https://contoso.sharepoint.com/sites/Marketing/Shared Documents/Plan.docx", "confidence": 0.9, "description": "For Exchange, the Exchange object ID. For SharePoint/OneDrive, the URL of the accessed item"},
        {"name": "Scope", "type": "string", "required": False, "example": "onmicrosoft", "confidence": 0.7, "description": "Scope of the event: online, onprem, hybrid, onmicrosoft"},

        # --- Entra ID / STS logon extensions ---
        {"name": "ActorIpAddress", "type": "string", "required": False, "example": "203.0.113.24", "confidence": 0.9, "description": "IP address of the actor (Entra ID events)"},
        {"name": "InterSystemsId", "type": "string", "required": False, "example": "ffffffff-eeee-dddd-cccc-bbbbbbbbbbbb", "confidence": 0.8, "description": "Cross-system tracking ID"},
        {"name": "IntraSystemId", "type": "string", "required": False, "example": "aaaaaaaa-1111-2222-3333-444444444444", "confidence": 0.8, "description": "Intra-system tracking ID"},
        {"name": "ApplicationId", "type": "string", "required": False, "example": "00000003-0000-0ff1-ce00-000000000000", "confidence": 0.9, "description": "GUID of the application involved"},
        {"name": "Actor", "type": "json", "required": False, "example": '[{"ID":"alice@contoso.onmicrosoft.com","Type":5},{"ID":"10033FFFA1234567","Type":3}]', "confidence": 0.8, "description": "List of identities of the actor"},
        {"name": "Target", "type": "json", "required": False, "example": '[{"ID":"bob@contoso.onmicrosoft.com","Type":5}]', "confidence": 0.8, "description": "List of identities of the target"},
        {"name": "ModifiedProperties", "type": "json", "required": False, "example": '[{"Name":"Included Updated Properties","OldValue":"","NewValue":"AccountEnabled, StrongAuthenticationMethod"}]', "confidence": 0.8, "description": "Modified properties for directory and admin events"},

        # --- SharePoint / OneDrive extensions ---
        {"name": "Site", "type": "string", "required": False, "example": "11111111-aaaa-bbbb-cccc-222222222222", "confidence": 0.8, "description": "GUID of the site where the file was accessed"},
        {"name": "ItemType", "type": "string", "required": False, "example": "File", "confidence": 0.9, "description": "Type of object: File, Folder, List, Web"},
        {"name": "EventSource", "type": "string", "required": False, "example": "SharePoint", "confidence": 0.8, "description": "Source of the event"},
        {"name": "SourceFileName", "type": "string", "required": False, "example": "Plan.docx", "confidence": 0.9, "description": "Name of the source file"},
        {"name": "SourceFileExtension", "type": "string", "required": False, "example": "docx", "confidence": 0.9, "description": "Extension of the source file"},
        {"name": "SourceRelativeUrl", "type": "string", "required": False, "example": "sites/Marketing/Shared Documents", "confidence": 0.8, "description": "Relative URL of the folder containing the source file"},
        {"name": "SiteUrl", "type": "string", "required": False, "example": "https://contoso.sharepoint.com/sites/Marketing/", "confidence": 0.9, "description": "URL of the site"},
        {"name": "UserAgent", "type": "string", "required": False, "example": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36", "confidence": 0.8, "description": "User agent of the client"},

        # --- Exchange extensions ---
        {"name": "MailboxOwnerUPN", "type": "string", "required": False, "example": "alice@contoso.onmicrosoft.com", "confidence": 0.8, "description": "UPN of the mailbox owner"},
        {"name": "ClientInfoString", "type": "string", "required": False, "example": "Client=OWA;Action=ViaProxy", "confidence": 0.7, "description": "Information about the email client used"},
        {"name": "LogonType", "type": "int", "required": False, "example": "0", "confidence": 0.7, "description": "Type of logon: 0=Owner, 1=Admin, 2=Delegate"},
    ],

    "sample_events": [
        {
            "raw": '{"CreationTime":"2026-04-12T14:22:17","Id":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee","Operation":"FileAccessed","OrganizationId":"11111111-2222-3333-4444-555555555555","RecordType":6,"ResultStatus":"Succeeded","UserKey":"i:0h.f|membership|10033ffffa1234567@live.com","UserType":0,"Version":1,"Workload":"SharePoint","ClientIP":"203.0.113.24","UserId":"alice@contoso.onmicrosoft.com","EventSource":"SharePoint","ItemType":"File","ListItemUniqueId":"cccccccc-1111-2222-3333-dddddddddddd","Site":"11111111-aaaa-bbbb-cccc-222222222222","SourceFileExtension":"docx","SourceFileName":"Plan.docx","SourceRelativeUrl":"sites/Marketing/Shared Documents","SiteUrl":"https://contoso.sharepoint.com/sites/Marketing/","UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36","ObjectId":"https://contoso.sharepoint.com/sites/Marketing/Shared Documents/Plan.docx"}',
            "subtype": "sharepoint_file_accessed",
        },
        {
            "raw": '{"CreationTime":"2026-04-12T14:35:02","Id":"bbbbbbbb-cccc-dddd-eeee-ffffffffffff","Operation":"UserLoggedIn","OrganizationId":"11111111-2222-3333-4444-555555555555","RecordType":15,"ResultStatus":"Succeeded","UserKey":"10033FFFA1234567@contoso.onmicrosoft.com","UserType":0,"Version":1,"Workload":"AzureActiveDirectory","ClientIP":"203.0.113.24","ObjectId":"00000003-0000-0000-c000-000000000000","UserId":"alice@contoso.onmicrosoft.com","AzureActiveDirectoryEventType":1,"ApplicationId":"00000003-0000-0000-c000-000000000000","ActorIpAddress":"203.0.113.24","InterSystemsId":"ffffffff-eeee-dddd-cccc-bbbbbbbbbbbb","IntraSystemId":"aaaaaaaa-1111-2222-3333-444444444444","Actor":[{"ID":"alice@contoso.onmicrosoft.com","Type":5},{"ID":"10033FFFA1234567","Type":3}],"ActorContextId":"11111111-2222-3333-4444-555555555555","Target":[{"ID":"00000003-0000-0000-c000-000000000000","Type":0}],"TargetContextId":"11111111-2222-3333-4444-555555555555"}',
            "subtype": "entraid_signin",
        },
        {
            "raw": '{"CreationTime":"2026-04-12T15:10:44","Id":"cccccccc-dddd-eeee-ffff-000000000000","Operation":"Add member to role.","OrganizationId":"11111111-2222-3333-4444-555555555555","RecordType":8,"ResultStatus":"Success","UserKey":"10033FFFA1234567@contoso.onmicrosoft.com","UserType":2,"Version":1,"Workload":"AzureActiveDirectory","ClientIP":"198.51.100.7","ObjectId":"bob@contoso.onmicrosoft.com","UserId":"admin@contoso.onmicrosoft.com","AzureActiveDirectoryEventType":0,"Actor":[{"ID":"admin@contoso.onmicrosoft.com","Type":5}],"Target":[{"ID":"bob@contoso.onmicrosoft.com","Type":5}],"ModifiedProperties":[{"Name":"Role.DisplayName","OldValue":"[]","NewValue":"[\\"Global Administrator\\"]"},{"Name":"Role.ObjectID","OldValue":"[]","NewValue":"[\\"62e90394-69f5-4237-9190-012177145e10\\"]"}]}',
            "subtype": "entraid_role_add",
        },
    ],

    "generator_hints": {
        "module_name": "generate_o365_management",
        "function_name": "generate_o365_management_logs",
        "volume_category": "saas_audit",
        "baseline_events_per_day": 2500,
        "subtypes": ["sharepoint_file_accessed", "sharepoint_file_modified", "sharepoint_file_downloaded", "onedrive_shared", "exchange_mailbox", "entraid_signin", "entraid_role_add", "teams_message"],
        "subtype_weights": {"sharepoint_file_accessed": 30, "sharepoint_file_modified": 15, "sharepoint_file_downloaded": 10, "onedrive_shared": 10, "exchange_mailbox": 15, "entraid_signin": 15, "teams_message": 3, "entraid_role_add": 2},
        "workloads": ["Exchange", "SharePoint", "OneDrive", "AzureActiveDirectory", "MicrosoftTeams", "SecurityComplianceCenter"],
        "operations": ["FileAccessed", "FileModified", "FileDownloaded", "FileUploaded", "FileDeleted", "SharingInvitationCreated", "UserLoggedIn", "Add member to role.", "MailItemsAccessed", "Send", "MessageSent"],
        "record_types": {"1": "ExchangeAdmin", "2": "ExchangeItem", "4": "SharePointFileOperation", "6": "SharePoint", "8": "AzureActiveDirectory", "15": "AzureActiveDirectoryStsLogon", "25": "MicrosoftTeams"},
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference", "kind": "vendor_doc", "trust": 0.98, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/4055", "kind": "splunkbase", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 88,
        "overall_confidence": 0.94,
    },
}
