"""Discovery spec for sap_audit. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "sap_audit",
        "display_name": "SAP Security Audit Log",
        "vendor": "SAP",
        "product": "SAP S/4HANA / NetWeaver",
        "description": "SAP Security Audit Log (SM20/RSAU) records security-relevant events in the SAP NetWeaver Application Server ABAP — logon attempts, transaction starts, report starts, RFC calls, and configuration changes. Events are written per application server and read via RSAU_READ_AUDITLOG_EXTERNAL or SM20 and typically forwarded as pipe-delimited text.",
    },

    "category": "erp",
    "source_groups": ["erp"],

    "format": {
        "type": "delimited",
        "confidence": 0.85,
        "delimiter": "|",
        "kv_separator": None,
        "quoted_values": False,
        "timestamp_fields": ["timestamp"],
        "timestamp_format": "YYYYMMDDHHMMSS",
    },

    "sourcetype": {
        "name": "sap:auditlog",
        "confidence": 0.95,
        "origin": "Splunkbase TA (app 3153) — Splunk Add-on for SAP",
    },

    "fields": [
        {"name": "timestamp", "type": "string", "required": True, "example": "20260412141522", "confidence": 1.0, "description": "Event timestamp in YYYYMMDDHHMMSS format (local time of application server)"},
        {"name": "system_id", "type": "string", "required": True, "example": "PRD", "confidence": 1.0, "description": "SAP system ID (SID) — 3-character system identifier"},
        {"name": "instance", "type": "string", "required": False, "example": "sapprd01_PRD_00", "confidence": 0.8, "description": "Application server instance name (host_SID_nr)"},
        {"name": "client", "type": "string", "required": True, "example": "100", "confidence": 1.0, "description": "SAP client (mandant) — 3-digit client number"},
        {"name": "user", "type": "string", "required": True, "example": "JSMITH", "confidence": 1.0, "description": "SAP user ID that generated the event (uppercase)"},
        {"name": "terminal", "type": "string", "required": False, "example": "WS-JSMITH-01", "confidence": 0.8, "description": "Terminal / workstation name the user connected from"},
        {"name": "transaction_code", "type": "string", "required": False, "example": "SU01", "confidence": 0.9, "description": "SAP transaction code (4-character) executed by the user"},
        {"name": "program", "type": "string", "required": False, "example": "SAPMSUU0", "confidence": 0.8, "description": "ABAP program name associated with the event"},
        {"name": "message_id", "type": "string", "required": True, "example": "AU1", "confidence": 1.0, "description": "Audit message ID (e.g., AU1=logon successful, AU2=logon failed, AUW=transaction start, AUK=report start)"},
        {"name": "message_text", "type": "string", "required": True, "example": "Logon successful (type=A)", "confidence": 1.0, "description": "Human-readable message text for the audit event"},
        {"name": "severity", "type": "string", "required": True, "example": "Non-Critical", "confidence": 0.9, "description": "Event severity: Non-Critical, Critical, Severe"},
        {"name": "audit_class", "type": "string", "required": True, "example": "Logon", "confidence": 0.95, "description": "Audit class: Logon, Transaction, Report, RFC/CPIC, User Master, System, Other"},
        {"name": "event_type", "type": "string", "required": False, "example": "successful_logon", "confidence": 0.7, "description": "Normalized event type string (derived from message_id)"},
    ],

    "sample_events": [
        {
            "raw": "20260412141522|PRD|sapprd01_PRD_00|100|JSMITH|WS-JSMITH-01|SU01|SAPMSUU0|AU1|Logon successful (type=A)|Non-Critical|Logon",
            "subtype": "logon_success",
        },
        {
            "raw": "20260412141855|PRD|sapprd01_PRD_00|100|MPATEL|WS-MPATEL-02|SE16|SAPLSETB|AU2|Logon failed (reason=2, type=A)|Critical|Logon",
            "subtype": "logon_failed",
        },
        {
            "raw": "20260412142110|PRD|sapprd02_PRD_01|100|JSMITH|WS-JSMITH-01|FB01|SAPMF05A|AUW|Transaction FB01 started|Non-Critical|Transaction",
            "subtype": "transaction_start",
        },
    ],

    "generator_hints": {
        "module_name": "generate_sap_audit",
        "function_name": "generate_sap_audit_logs",
        "volume_category": "erp",
        "baseline_events_per_day": 2000,
        "message_ids": ["AU1", "AU2", "AU3", "AUW", "AUK", "AUO", "AUP", "AUQ", "AUR"],
        "message_id_weights": {"AU1": 40, "AUW": 30, "AUK": 15, "AU2": 5, "AUO": 4, "AUP": 3, "AUQ": 2, "AUR": 1},
        "severities": ["Non-Critical", "Critical", "Severe"],
        "severity_weights": {"Non-Critical": 85, "Critical": 12, "Severe": 3},
        "audit_classes": ["Logon", "Transaction", "Report", "RFC/CPIC", "User Master", "System", "Other"],
        "common_transactions": ["SU01", "SU10", "SE16", "SE38", "SM30", "FB01", "FB60", "VA01", "ME21N", "PA20", "PA30", "MIGO"],
        "system_ids": ["PRD", "QAS", "DEV"],
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://help.sap.com/docs/SAP_NETWEAVER_750/280f016edb8049e998237fcbd80558e7/c7a39c3be8ccf2e8e10000000a174cb4.html", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/3153", "kind": "splunkbase", "trust": 0.9, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 55,
        "overall_confidence": 0.85,
    },
}
