"""Discovery spec for sysmon. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "sysmon",
        "display_name": "Microsoft Sysmon",
        "vendor": "Microsoft",
        "product": "Sysmon (System Monitor)",
        "description": "Sysinternals System Monitor (Sysmon) provides rich host-level telemetry for process creation, network connections, image loads, file creation, registry activity, and DNS queries. Events are written to the Microsoft-Windows-Sysmon/Operational channel and collected by the Splunk Universal Forwarder.",
    },

    "category": "windows",
    "source_groups": ["windows", "endpoint"],

    "format": {
        "type": "kv",
        "confidence": 0.90,
        "delimiter": "\n",
        "kv_separator": ": ",
        "quoted_values": False,
        "timestamp_fields": ["UtcTime", "_time"],
        "timestamp_format": "YYYY-MM-DD HH:MM:SS.sss (UtcTime), MM/DD/YYYY hh:mm:ss AM/PM (event header)",
    },

    "sourcetype": {
        "name": "WinEventLog:Microsoft-Windows-Sysmon/Operational",
        "confidence": 0.99,
        "origin": "Splunkbase TA (app 5709) — Splunk Add-on for Sysmon",
    },

    "fields": [
        # --- Event header ---
        {"name": "EventCode", "type": "int", "required": True, "example": "1", "confidence": 1.0, "description": "Sysmon event ID (1=ProcessCreate, 3=NetworkConnect, 7=ImageLoad, 10=ProcessAccess, 11=FileCreate, 12/13/14=Registry, 22=DNSQuery)"},
        {"name": "EventType", "type": "string", "required": True, "example": "Information", "confidence": 1.0, "description": "Event level"},
        {"name": "Computer", "type": "string", "required": True, "example": "WS-ENG-0073", "confidence": 1.0, "description": "Hostname that generated the event"},
        {"name": "UtcTime", "type": "string", "required": True, "example": "2024-08-14 13:42:18.193", "confidence": 1.0, "description": "UTC timestamp of the event action"},
        {"name": "RuleName", "type": "string", "required": False, "example": "technique_id=T1059,technique_name=CommandLineInterface", "confidence": 0.7, "description": "Rule name from Sysmon config that matched"},

        # --- Process identity ---
        {"name": "ProcessGuid", "type": "string", "required": True, "example": "{9f1af44e-2c1e-65bc-1a00-000000001b00}", "confidence": 1.0, "description": "Unique GUID for the process instance"},
        {"name": "ProcessId", "type": "int", "required": True, "example": "4812", "confidence": 1.0, "description": "Operating system process ID"},
        {"name": "Image", "type": "string", "required": True, "example": "C:\\\\Windows\\\\System32\\\\cmd.exe", "confidence": 1.0, "description": "Full path to the executable"},
        {"name": "FileVersion", "type": "string", "required": False, "example": "10.0.19041.1 (WinBuild.160101.0800)", "confidence": 0.8, "description": "Executable file version"},
        {"name": "Description", "type": "string", "required": False, "example": "Windows Command Processor", "confidence": 0.8, "description": "File description from PE metadata"},
        {"name": "Product", "type": "string", "required": False, "example": "Microsoft Windows Operating System", "confidence": 0.8, "description": "Product name from PE metadata"},
        {"name": "Company", "type": "string", "required": False, "example": "Microsoft Corporation", "confidence": 0.8, "description": "Company name from PE metadata"},
        {"name": "OriginalFileName", "type": "string", "required": False, "example": "Cmd.Exe", "confidence": 0.7, "description": "Original file name from PE metadata"},
        {"name": "CommandLine", "type": "string", "required": True, "example": "\"cmd.exe\" /c whoami", "confidence": 1.0, "description": "Full command line used to launch the process"},
        {"name": "CurrentDirectory", "type": "string", "required": False, "example": "C:\\\\Users\\\\jsmith\\\\", "confidence": 0.8, "description": "Working directory of the process"},
        {"name": "User", "type": "string", "required": True, "example": "CORP\\\\jsmith", "confidence": 1.0, "description": "User context that executed the process"},
        {"name": "LogonGuid", "type": "string", "required": False, "example": "{9f1af44e-1a22-65bc-ab02-000000000000}", "confidence": 0.8, "description": "GUID of the logon session"},
        {"name": "LogonId", "type": "string", "required": False, "example": "0x2ab29f", "confidence": 0.8, "description": "Hex logon session ID"},
        {"name": "TerminalSessionId", "type": "int", "required": False, "example": "1", "confidence": 0.8, "description": "Terminal Services session ID"},
        {"name": "IntegrityLevel", "type": "string", "required": False, "example": "Medium", "confidence": 0.8, "description": "Mandatory Integrity Level (Low, Medium, High, System)"},
        {"name": "Hashes", "type": "string", "required": False, "example": "SHA256=9F914D42706FE215501044ACD85A32D58AAEF1419D404FDDFA5D3B48F66CCD9F,IMPHASH=272245E2988E1E430500B852C4FB5E18", "confidence": 0.9, "description": "File hashes per Sysmon config (MD5, SHA1, SHA256, IMPHASH)"},

        # --- Parent process ---
        {"name": "ParentProcessGuid", "type": "string", "required": False, "example": "{9f1af44e-1a22-65bc-0900-000000001b00}", "confidence": 0.9, "description": "GUID of the parent process"},
        {"name": "ParentProcessId", "type": "int", "required": False, "example": "2312", "confidence": 0.9, "description": "OS process ID of the parent"},
        {"name": "ParentImage", "type": "string", "required": False, "example": "C:\\\\Windows\\\\explorer.exe", "confidence": 0.9, "description": "Full path of the parent executable"},
        {"name": "ParentCommandLine", "type": "string", "required": False, "example": "C:\\\\Windows\\\\Explorer.EXE", "confidence": 0.9, "description": "Command line of the parent process"},
        {"name": "ParentUser", "type": "string", "required": False, "example": "CORP\\\\jsmith", "confidence": 0.8, "description": "User context of the parent process"},

        # --- Network connection (EventCode 3) ---
        {"name": "Protocol", "type": "string", "required": False, "example": "tcp", "confidence": 0.8, "description": "Network protocol (tcp, udp)"},
        {"name": "Initiated", "type": "string", "required": False, "example": "true", "confidence": 0.8, "description": "Whether the connection was initiated by this host"},
        {"name": "SourceIp", "type": "ipv4", "required": False, "example": "10.24.14.88", "confidence": 0.9, "description": "Source IP address"},
        {"name": "SourceHostname", "type": "string", "required": False, "example": "WS-ENG-0073", "confidence": 0.7, "description": "Source hostname"},
        {"name": "SourcePort", "type": "int", "required": False, "example": "49822", "confidence": 0.9, "description": "Source TCP/UDP port"},
        {"name": "DestinationIp", "type": "ipv4", "required": False, "example": "104.18.12.77", "confidence": 0.9, "description": "Destination IP address"},
        {"name": "DestinationHostname", "type": "string", "required": False, "example": "updates.example.com", "confidence": 0.7, "description": "Destination hostname (if resolved)"},
        {"name": "DestinationPort", "type": "int", "required": False, "example": "443", "confidence": 0.9, "description": "Destination TCP/UDP port"},
        {"name": "DestinationPortName", "type": "string", "required": False, "example": "https", "confidence": 0.7, "description": "IANA name of destination port"},

        # --- File / registry / DNS ---
        {"name": "TargetFilename", "type": "string", "required": False, "example": "C:\\\\Users\\\\jsmith\\\\AppData\\\\Local\\\\Temp\\\\installer.tmp", "confidence": 0.8, "description": "Target filename for FileCreate events (EventCode 11)"},
        {"name": "CreationUtcTime", "type": "string", "required": False, "example": "2024-08-14 13:42:18.112", "confidence": 0.7, "description": "File creation UTC time"},
        {"name": "TargetObject", "type": "string", "required": False, "example": "HKLM\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run\\\\updater", "confidence": 0.7, "description": "Registry target object path (EventCodes 12/13/14)"},
        {"name": "Details", "type": "string", "required": False, "example": "C:\\\\Users\\\\jsmith\\\\AppData\\\\Roaming\\\\upd.exe", "confidence": 0.7, "description": "Registry value details"},
        {"name": "QueryName", "type": "string", "required": False, "example": "updates.example.com", "confidence": 0.8, "description": "DNS query name (EventCode 22)"},
        {"name": "QueryStatus", "type": "string", "required": False, "example": "0", "confidence": 0.8, "description": "DNS query status code"},
        {"name": "QueryResults", "type": "string", "required": False, "example": "type: 5 cdn.example.com;::ffff:104.18.12.77;", "confidence": 0.7, "description": "DNS query results list"},
    ],

    "sample_events": [
        {
            "raw": "08/14/2024 01:42:18 PM\nLogName=Microsoft-Windows-Sysmon/Operational\nSourceName=Microsoft-Windows-Sysmon\nEventCode=1\nEventType=Information\nComputer=WS-ENG-0073\nTaskCategory=Process Create (rule: ProcessCreate)\nRuleName=-\nUtcTime: 2024-08-14 13:42:18.193\nProcessGuid: {9f1af44e-2c1e-65bc-1a00-000000001b00}\nProcessId: 4812\nImage: C:\\\\Windows\\\\System32\\\\cmd.exe\nFileVersion: 10.0.19041.1 (WinBuild.160101.0800)\nDescription: Windows Command Processor\nProduct: Microsoft Windows Operating System\nCompany: Microsoft Corporation\nOriginalFileName: Cmd.Exe\nCommandLine: \"cmd.exe\" /c whoami\nCurrentDirectory: C:\\\\Users\\\\jsmith\\\\\nUser: CORP\\\\jsmith\nLogonGuid: {9f1af44e-1a22-65bc-ab02-000000000000}\nLogonId: 0x2ab29f\nTerminalSessionId: 1\nIntegrityLevel: Medium\nHashes: SHA256=9F914D42706FE215501044ACD85A32D58AAEF1419D404FDDFA5D3B48F66CCD9F,IMPHASH=272245E2988E1E430500B852C4FB5E18\nParentProcessGuid: {9f1af44e-1a22-65bc-0900-000000001b00}\nParentProcessId: 2312\nParentImage: C:\\\\Windows\\\\explorer.exe\nParentCommandLine: C:\\\\Windows\\\\Explorer.EXE\nParentUser: CORP\\\\jsmith",
            "subtype": "process_create",
        },
        {
            "raw": "08/14/2024 01:42:21 PM\nLogName=Microsoft-Windows-Sysmon/Operational\nEventCode=3\nEventType=Information\nComputer=WS-ENG-0073\nTaskCategory=Network connection detected (rule: NetworkConnect)\nUtcTime: 2024-08-14 13:42:21.417\nProcessGuid: {9f1af44e-2c1e-65bc-1a00-000000001b00}\nProcessId: 4812\nImage: C:\\\\Windows\\\\System32\\\\cmd.exe\nUser: CORP\\\\jsmith\nProtocol: tcp\nInitiated: true\nSourceIsIpv6: false\nSourceIp: 10.24.14.88\nSourceHostname: WS-ENG-0073\nSourcePort: 49822\nDestinationIsIpv6: false\nDestinationIp: 104.18.12.77\nDestinationHostname: updates.example.com\nDestinationPort: 443\nDestinationPortName: https",
            "subtype": "network_connect",
        },
        {
            "raw": "08/14/2024 01:45:02 PM\nLogName=Microsoft-Windows-Sysmon/Operational\nEventCode=22\nEventType=Information\nComputer=WS-ENG-0073\nTaskCategory=Dns query (rule: DnsQuery)\nUtcTime: 2024-08-14 13:45:02.911\nProcessGuid: {9f1af44e-2c1e-65bc-1a00-000000001b00}\nProcessId: 4812\nQueryName: updates.example.com\nQueryStatus: 0\nQueryResults: type: 5 cdn.example.com;::ffff:104.18.12.77;\nImage: C:\\\\Windows\\\\System32\\\\cmd.exe\nUser: CORP\\\\jsmith",
            "subtype": "dns_query",
        },
    ],

    "generator_hints": {
        "module_name": "generate_sysmon",
        "function_name": "generate_sysmon_logs",
        "volume_category": "endpoint",
        "baseline_events_per_day": 5000,
        "subtypes": ["process_create", "network_connect", "image_loaded", "process_access", "file_create", "registry_set", "dns_query"],
        "subtype_weights": {"process_create": 30, "network_connect": 25, "dns_query": 20, "file_create": 10, "image_loaded": 8, "registry_set": 5, "process_access": 2},
        "event_codes": {
            "1": "Process creation",
            "3": "Network connection",
            "7": "Image loaded",
            "10": "Process accessed",
            "11": "File created",
            "12": "Registry object added or deleted",
            "13": "Registry value set",
            "14": "Registry object renamed",
            "22": "DNS query",
        },
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://github.com/SwiftOnSecurity/sysmon-config", "kind": "community", "trust": 0.85, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/5709", "kind": "splunkbase", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 101,
        "overall_confidence": 0.89,
    },
}
