"""Discovery spec for wineventlog_security. Generated by fd-discover."""

PRESET = {
    "schema_version": 1,
    "generated_at": "2026-04-12T00:00:00Z",
    "generated_by": "fd-discover v0.1.0",

    "source": {
        "id": "wineventlog_security",
        "display_name": "Windows Security Event Log",
        "vendor": "Microsoft",
        "product": "Windows Security Log",
        "description": "Windows Security channel events collected by the Splunk Universal Forwarder. Captures authentication, account management, privilege use, and audit policy events in a multi-line key-value pair format keyed by Event ID.",
    },

    "category": "windows",
    "source_groups": ["windows", "endpoint"],

    # ─── Indexed-time field overrides (consumed by fd-build-app) ────────
    # ComputerName carries the real host inside each event — overrides
    # the default Splunk host (forwarder hostname). LogName splits one
    # log stream into FAKE:WinEventLog:System / Application / Security.
    "host_field": "ComputerName",
    "sourcetype_routing": {
        "field": "LogName",
        "template": "FAKE:WinEventLog:{value}",
    },

    "format": {
        "type": "kv",
        "confidence": 0.90,
        "delimiter": "\n",
        "kv_separator": "=",
        "quoted_values": False,
        "timestamp_fields": ["_time"],
        "timestamp_format": "MM/DD/YYYY hh:mm:ss AM/PM (Windows event log header)",
    },

    "sourcetype": {
        "name": "WinEventLog:Security",
        "confidence": 0.99,
        "origin": "Splunkbase TA (app 742) — Splunk Add-on for Microsoft Windows",
    },

    "fields": [
        # --- Event header fields ---
        {"name": "EventCode", "type": "int", "required": True, "example": "4624", "confidence": 1.0, "description": "Windows Event ID identifying the specific security event"},
        {"name": "EventType", "type": "int", "required": True, "example": "0", "confidence": 1.0, "description": "Legacy event type (0=Success, 1=Error, 2=Warning, 4=Information, 8=Success Audit, 16=Failure Audit)"},
        {"name": "Type", "type": "string", "required": True, "example": "Information", "confidence": 1.0, "description": "Event level: Information, Warning, Error, Success Audit, Failure Audit"},
        {"name": "ComputerName", "type": "string", "required": True, "example": "WS-FIN-0042", "confidence": 1.0, "description": "Hostname of the computer that generated the event"},
        {"name": "SourceName", "type": "string", "required": True, "example": "Microsoft Windows security auditing.", "confidence": 1.0, "description": "Event log provider name"},
        {"name": "LogName", "type": "string", "required": True, "example": "Security", "confidence": 1.0, "description": "Windows event log channel name"},
        {"name": "RecordNumber", "type": "int", "required": True, "example": "1928374", "confidence": 1.0, "description": "Monotonically increasing event record number"},
        {"name": "Keywords", "type": "string", "required": True, "example": "Audit Success", "confidence": 1.0, "description": "Event keywords: Audit Success or Audit Failure"},
        {"name": "TaskCategory", "type": "string", "required": True, "example": "Logon", "confidence": 1.0, "description": "Human-readable task category (Logon, Logoff, Account Management, etc.)"},
        {"name": "OpCode", "type": "string", "required": False, "example": "Info", "confidence": 0.8, "description": "Event opcode"},
        {"name": "Message", "type": "string", "required": True, "example": "An account was successfully logged on.", "confidence": 1.0, "description": "Human-readable message header for the event"},

        # --- User/account fields ---
        {"name": "User", "type": "string", "required": True, "example": "CORP\\\\jsmith", "confidence": 1.0, "description": "User context the event ran under (DOMAIN\\\\user)"},
        {"name": "Sid", "type": "string", "required": True, "example": "S-1-5-21-1004336348-1177238915-682003330-1001", "confidence": 1.0, "description": "Security Identifier of the subject user"},
        {"name": "SidType", "type": "string", "required": False, "example": "0x1", "confidence": 0.8, "description": "SID type code"},
        {"name": "Account_Name", "type": "string", "required": True, "example": "jsmith", "confidence": 1.0, "description": "Target account username (from event body)"},
        {"name": "Account_Domain", "type": "string", "required": True, "example": "CORP", "confidence": 1.0, "description": "Target account domain (from event body)"},
        {"name": "Security_ID", "type": "string", "required": False, "example": "CORP\\\\jsmith", "confidence": 0.9, "description": "Target Security ID field in Account Information block"},

        # --- Logon-specific fields ---
        {"name": "Logon_ID", "type": "string", "required": False, "example": "0x3E7A9B2", "confidence": 0.9, "description": "Hex logon session identifier"},
        {"name": "Logon_Type", "type": "int", "required": False, "example": "3", "confidence": 0.9, "description": "Logon type: 2=Interactive, 3=Network, 4=Batch, 5=Service, 7=Unlock, 10=RemoteInteractive, 11=CachedInteractive"},
        {"name": "Logon_Process", "type": "string", "required": False, "example": "NtLmSsp", "confidence": 0.8, "description": "Name of the logon process"},
        {"name": "Authentication_Package", "type": "string", "required": False, "example": "NTLM", "confidence": 0.8, "description": "Auth package used (NTLM, Kerberos, Negotiate)"},
        {"name": "Workstation_Name", "type": "string", "required": False, "example": "WS-FIN-0042", "confidence": 0.8, "description": "Name of the workstation from which logon originated"},
        {"name": "Source_Network_Address", "type": "ipv4", "required": False, "example": "10.24.14.88", "confidence": 0.9, "description": "IP address of the client that requested the logon"},
        {"name": "Source_Port", "type": "int", "required": False, "example": "49812", "confidence": 0.8, "description": "Source port of the client that requested the logon"},
        {"name": "Impersonation_Level", "type": "string", "required": False, "example": "Impersonation", "confidence": 0.7, "description": "Impersonation level granted to the logon"},
        {"name": "Key_Length", "type": "int", "required": False, "example": "128", "confidence": 0.7, "description": "Length of the authentication key"},
        {"name": "Failure_Reason", "type": "string", "required": False, "example": "Unknown user name or bad password.", "confidence": 0.8, "description": "Reason a logon failed (EventCode 4625)"},
        {"name": "Status", "type": "string", "required": False, "example": "0xC000006D", "confidence": 0.8, "description": "NTSTATUS code for the logon result"},
        {"name": "Sub_Status", "type": "string", "required": False, "example": "0xC000006A", "confidence": 0.7, "description": "NTSTATUS sub-status code"},

        # --- Process information ---
        {"name": "Process_ID", "type": "string", "required": False, "example": "0x1f8", "confidence": 0.8, "description": "Hex process ID associated with the event"},
        {"name": "Process_Name", "type": "string", "required": False, "example": "C:\\\\Windows\\\\System32\\\\svchost.exe", "confidence": 0.8, "description": "Full path of the process that triggered the event"},
        {"name": "Caller_Process_Name", "type": "string", "required": False, "example": "C:\\\\Windows\\\\System32\\\\lsass.exe", "confidence": 0.7, "description": "Process that invoked the action"},

        # --- Privilege / account management ---
        {"name": "Privileges", "type": "string", "required": False, "example": "SeSecurityPrivilege SeBackupPrivilege", "confidence": 0.7, "description": "List of privileges assigned (EventCode 4672)"},
        {"name": "Target_Account_Name", "type": "string", "required": False, "example": "newuser01", "confidence": 0.7, "description": "Target account name for account management events"},
        {"name": "Target_Domain", "type": "string", "required": False, "example": "CORP", "confidence": 0.7, "description": "Target domain for account management events"},
    ],

    "sample_events": [
        {
            "raw": "08/14/2024 09:23:41 AM\nLogName=Security\nSourceName=Microsoft Windows security auditing.\nEventCode=4624\nEventType=0\nType=Information\nComputerName=WS-FIN-0042\nTaskCategory=Logon\nOpCode=Info\nRecordNumber=1928374\nKeywords=Audit Success\nMessage=An account was successfully logged on.\n\nSubject:\n\tSecurity ID:\t\tS-1-5-18\n\tAccount Name:\t\tWS-FIN-0042$\n\tAccount Domain:\t\tCORP\n\tLogon ID:\t\t0x3E7\n\nLogon Information:\n\tLogon Type:\t\t3\n\tRestricted Admin Mode:\t-\n\tVirtual Account:\t\tNo\n\tElevated Token:\t\tNo\n\nNew Logon:\n\tSecurity ID:\t\tS-1-5-21-1004336348-1177238915-682003330-1001\n\tAccount Name:\t\tjsmith\n\tAccount Domain:\t\tCORP\n\tLogon ID:\t\t0x3E7A9B2\n\nNetwork Information:\n\tWorkstation Name:\tWS-FIN-0042\n\tSource Network Address:\t10.24.14.88\n\tSource Port:\t\t49812\n\nDetailed Authentication Information:\n\tLogon Process:\t\tNtLmSsp\n\tAuthentication Package:\tNTLM\n\tKey Length:\t\t128",
            "subtype": "logon_success",
        },
        {
            "raw": "08/14/2024 09:24:02 AM\nLogName=Security\nSourceName=Microsoft Windows security auditing.\nEventCode=4625\nEventType=0\nType=Information\nComputerName=WS-HR-0011\nTaskCategory=Logon\nKeywords=Audit Failure\nMessage=An account failed to log on.\n\nSubject:\n\tSecurity ID:\t\tS-1-0-0\n\tAccount Name:\t\t-\n\tAccount Domain:\t\t-\n\nAccount For Which Logon Failed:\n\tSecurity ID:\t\tS-1-0-0\n\tAccount Name:\t\tadministrator\n\tAccount Domain:\t\tCORP\n\nFailure Information:\n\tFailure Reason:\t\tUnknown user name or bad password.\n\tStatus:\t\t\t0xC000006D\n\tSub Status:\t\t0xC000006A\n\nProcess Information:\n\tCaller Process Name:\tC:\\\\Windows\\\\System32\\\\lsass.exe\n\nNetwork Information:\n\tWorkstation Name:\tWS-HR-0011\n\tSource Network Address:\t192.168.5.210\n\tSource Port:\t\t50122",
            "subtype": "logon_failure",
        },
        {
            "raw": "08/14/2024 10:02:17 AM\nLogName=Security\nSourceName=Microsoft Windows security auditing.\nEventCode=4720\nEventType=0\nType=Information\nComputerName=DC-01\nTaskCategory=User Account Management\nKeywords=Audit Success\nMessage=A user account was created.\n\nSubject:\n\tSecurity ID:\t\tS-1-5-21-1004336348-1177238915-682003330-500\n\tAccount Name:\t\tadministrator\n\tAccount Domain:\t\tCORP\n\tLogon ID:\t\t0x2A3F8\n\nNew Account:\n\tSecurity ID:\t\tS-1-5-21-1004336348-1177238915-682003330-1122\n\tAccount Name:\t\tnewuser01\n\tAccount Domain:\t\tCORP",
            "subtype": "account_created",
        },
    ],

    "generator_hints": {
        "module_name": "generate_wineventlog_security",
        "function_name": "generate_wineventlog_security_logs",
        "volume_category": "endpoint",
        "baseline_events_per_day": 2000,
        "subtypes": ["logon_success", "logon_failure", "logoff", "privileged_logon", "account_created", "account_deleted", "account_changed", "explicit_creds"],
        "subtype_weights": {"logon_success": 55, "logoff": 20, "logon_failure": 10, "privileged_logon": 8, "explicit_creds": 3, "account_created": 2, "account_changed": 1, "account_deleted": 1},
        "event_codes": {
            "4624": "An account was successfully logged on",
            "4625": "An account failed to log on",
            "4634": "An account was logged off",
            "4648": "A logon was attempted using explicit credentials",
            "4672": "Special privileges assigned to new logon",
            "4720": "A user account was created",
            "4726": "A user account was deleted",
            "4738": "A user account was changed",
        },
        "logon_types": {"2": "Interactive", "3": "Network", "4": "Batch", "5": "Service", "7": "Unlock", "10": "RemoteInteractive", "11": "CachedInteractive"},
    },

    "research_metadata": {
        "sources_consulted": [
            {"url": "https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4625", "kind": "vendor_doc", "trust": 0.95, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://splunkbase.splunk.com/app/742", "kind": "splunkbase", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
            {"url": "https://docs.splunk.com/Documentation/AddOns/released/MSWindows/Sourcetypes", "kind": "vendor_doc", "trust": 0.90, "retrieved_at": "2026-04-12T00:00:00Z"},
        ],
        "total_samples_found": 3,
        "research_mode": "full",
        "elapsed_sec": 92,
        "overall_confidence": 0.90,
    },
}
