#!/usr/bin/env python3
"""
TEMPLATE generator — copy this file and customize for your data source.

Generated by fake-data:add-generator. This file is yours — edit freely.

Usage:
    Standalone:   python3 fake_data/generators/generate_TEMPLATE.py --days=1
    Orchestrator: python3 fake_data/main_generate.py --sources=TEMPLATE
"""

import json
import random
import sys
from pathlib import Path
from typing import Dict, List, Optional

# Bootstrap sys.path so this file runs standalone
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from fake_data.world import USERS, LOCATIONS, NETWORK_CONFIG, EXTERNAL_IP_POOL
from fake_data.config import (
    DEFAULT_START_DATE, DEFAULT_DAYS, DEFAULT_SCALE,
    get_output_path, expand_scenarios,
)
from fake_data.time_utils import ts_iso, calc_natural_events, date_add

# =============================================================================
# SOURCE METADATA — read by main_generate.py for discovery and orchestration
# =============================================================================

SOURCE_META = {
    "source_id": "TEMPLATE",
    # category MUST be one of: network, cloud, windows, linux, web, retail,
    # collaboration, itsm, erp, ot, database. Never "unknown".
    "category": "network",
    "source_groups": ["network"],
    "volume_category": "firewall",
    "multi_file": False,
    "depends_on": [],
    "description": "Template generator — replace with your source description",

    # ─── OPTIONAL: indexed-time field overrides ──────────────────────────
    # Read by fd-build-app to write transforms.conf stanzas. Leave unset
    # if the source has no in-event host or no per-event sourcetype split.

    # Override Splunk's default host (forwarder hostname) with a value
    # from inside the event. The regex must capture exactly one group.
    # Example: "ComputerName=(\\S+)" for WinEventLog
    # "host_field": None,        # field name shorthand, e.g. "ComputerName"
    # "host_regex": None,        # explicit regex override (takes precedence)

    # Route to multiple sourcetypes based on a field value inside the
    # event. Example: WinEventLog:System / Application / Security all
    # share one log format, distinguished by the LogName= field.
    # "sourcetype_routing": {
    #     "field": "LogName",
    #     "template": "FAKE:WinEventLog:{value}",  # {value} is replaced at index time
    # },

    # ─── OPTIONAL: Magic 6 props.conf overrides ──────────────────────────
    # fd-build-app ALWAYS writes SHOULD_LINEMERGE, LINE_BREAKER, TIME_PREFIX,
    # TIME_FORMAT, MAX_TIMESTAMP_LOOKAHEAD, TRUNCATE on every [FAKE:<id>]
    # stanza. If you leave this dict unset, fd-build-app uses format-defaults.
    # Set ONLY the keys you need to override — e.g. multi-line events need
    # a custom LINE_BREAKER that splits on the next event header.
    #
    # "props_overrides": {
    #     "LINE_BREAKER": r"([\r\n]+)(?=\d{4}-\d{2}-\d{2})",
    #     "TIME_PREFIX": "^",
    #     "TIME_FORMAT": "%Y-%m-%d %H:%M:%S",
    #     "MAX_TIMESTAMP_LOOKAHEAD": 30,
    #     "TRUNCATE": 50000,
    # },
}


# =============================================================================
# GENERATOR FUNCTION
# =============================================================================

def generate_TEMPLATE_logs(
    start_date: str = DEFAULT_START_DATE,
    days: int = DEFAULT_DAYS,
    scale: float = DEFAULT_SCALE,
    scenarios: str = "none",
    output_file: str = None,
    progress_callback=None,
    quiet: bool = False,
) -> int:
    """Generate TEMPLATE log events.

    Returns the number of events generated.
    """
    events = []
    active_scenarios = expand_scenarios(scenarios, start_date=start_date)

    for day in range(days):
        if progress_callback:
            progress_callback(SOURCE_META["source_id"], day, days)

        for hour in range(24):
            count = calc_natural_events(
                base_count=int(100 * scale),
                start_date=start_date,
                day_offset=day,
                hour=hour,
                category=SOURCE_META["volume_category"],
            )

            for _ in range(count):
                minute = random.randint(0, 59)
                second = random.randint(0, 59)
                events.append(_make_event(start_date, day, hour, minute, second))

            # Inject scenario events (returned as pre-formatted strings)
            for scenario in active_scenarios:
                method = getattr(scenario, f"{SOURCE_META['source_id']}_hour", None)
                if method:
                    for line in method(day, hour):
                        events.append({"timestamp": ts_iso(start_date, day, hour,
                                        random.randint(0, 59), random.randint(0, 59)),
                                        "_scenario_line": line})

    # Sort by timestamp for realistic ordering
    events.sort(key=lambda e: e.get("timestamp", ""))

    # Write output
    output_path = Path(output_file) if output_file else get_output_path(
        SOURCE_META["category"],
        f"{SOURCE_META['source_id']}.log",
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        for event in events:
            if "_scenario_line" in event:
                f.write(event["_scenario_line"] + "\n")
            else:
                f.write(_serialize(event) + "\n")

    if not quiet:
        print(f"  {SOURCE_META['source_id']}: {len(events):,} events "
              f"-> {output_path}")

    return len(events)


# =============================================================================
# EVENT CONSTRUCTION — customize these for your source
# =============================================================================

def _make_event(start_date: str, day: int, hour: int,
                minute: int, second: int) -> Dict:
    """Construct one log event. Customize fields for your source."""
    user = random.choice(USERS)
    return {
        "timestamp": ts_iso(start_date, day, hour, minute, second),
        "user": user["username"],
        "action": random.choice(["login", "logout", "access", "modify"]),
        "status": random.choice(["success", "failure"]),
        "source_ip": f"10.{random.randint(1,254)}.{random.randint(1,254)}.{random.randint(1,254)}",
        # Scenario events set "demo_id" via their _hour() methods.
        # Baseline events leave demo_id unset.
    }


def _serialize(event: Dict) -> str:
    """Serialize one event to a log line. Change for KV, syslog, CSV, etc."""
    return json.dumps(event)


# =============================================================================
# STANDALONE EXECUTION
# =============================================================================

if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description=f"Generate {SOURCE_META['source_id']} logs")
    p.add_argument("--start-date", default=DEFAULT_START_DATE)
    p.add_argument("--days", type=int, default=DEFAULT_DAYS)
    p.add_argument("--scale", type=float, default=DEFAULT_SCALE)
    p.add_argument("--scenarios", default="none")
    p.add_argument("--output", default=None, help="Override output file path")
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args()

    count = generate_TEMPLATE_logs(
        start_date=args.start_date,
        days=args.days,
        scale=args.scale,
        scenarios=args.scenarios,
        output_file=args.output,
        quiet=args.quiet,
    )
    if not args.quiet:
        print(f"\nTotal: {count:,} events")
